"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from setuptools import find_packages, setup  # noqa: H301


# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "mcp-client"
VERSION = "2.8.0"
PYTHON_REQUIRES = ">= 3.9"
# Dependencies are defined in pyproject.toml (UV-native)
# This setup.py reads from pyproject.toml instead of hardcoding dependencies
try:
    import tomllib
except ImportError:
    import tomli as tomllib

# Read dependencies from pyproject.toml (single source of truth)
with open("pyproject.toml", "rb") as f:
    pyproject_data = tomllib.load(f)
    REQUIRES = pyproject_data["project"]["dependencies"]

setup(
    name=NAME,
    version=VERSION,
    description="MCP Server with LangGraph",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "MCP Server with LangGraph"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type="text/markdown",
    long_description="""\
    AI Agent with fine-grained authorization and observability - StreamableHTTP transport
    """,  # noqa: E501
    package_data={"mcp_client": ["py.typed"]},
)
