/*
MCP Server with LangGraph

Testing APIKeysAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mcpclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_mcpclient_APIKeysAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test APIKeysAPIService CreateApiKeyApiV1ApiKeysPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.CreateApiKeyApiV1ApiKeysPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService ListApiKeysApiV1ApiKeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.ListApiKeysApiV1ApiKeysGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RevokeApiKeyApiV1ApiKeysKeyIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId string

		httpRes, err := apiClient.APIKeysAPI.RevokeApiKeyApiV1ApiKeysKeyIdDelete(context.Background(), keyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RotateApiKeyApiV1ApiKeysKeyIdRotatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId string

		resp, httpRes, err := apiClient.APIKeysAPI.RotateApiKeyApiV1ApiKeysKeyIdRotatePost(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
