/*
MCP Server with LangGraph

Testing ServicePrincipalsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mcpclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_mcpclient_ServicePrincipalsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ServicePrincipalsAPIService AssociateServicePrincipalWithUserApiV1ServicePrincipalsServiceIdAssociateUserPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serviceId string

		resp, httpRes, err := apiClient.ServicePrincipalsAPI.AssociateServicePrincipalWithUserApiV1ServicePrincipalsServiceIdAssociateUserPost(context.Background(), serviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicePrincipalsAPIService CreateServicePrincipalApiV1ServicePrincipalsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ServicePrincipalsAPI.CreateServicePrincipalApiV1ServicePrincipalsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicePrincipalsAPIService DeleteServicePrincipalApiV1ServicePrincipalsServiceIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serviceId string

		httpRes, err := apiClient.ServicePrincipalsAPI.DeleteServicePrincipalApiV1ServicePrincipalsServiceIdDelete(context.Background(), serviceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicePrincipalsAPIService GetServicePrincipalApiV1ServicePrincipalsServiceIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serviceId string

		resp, httpRes, err := apiClient.ServicePrincipalsAPI.GetServicePrincipalApiV1ServicePrincipalsServiceIdGet(context.Background(), serviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicePrincipalsAPIService ListServicePrincipalsApiV1ServicePrincipalsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ServicePrincipalsAPI.ListServicePrincipalsApiV1ServicePrincipalsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicePrincipalsAPIService RotateServicePrincipalSecretApiV1ServicePrincipalsServiceIdRotateSecretPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serviceId string

		resp, httpRes, err := apiClient.ServicePrincipalsAPI.RotateServicePrincipalSecretApiV1ServicePrincipalsServiceIdRotateSecretPost(context.Background(), serviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
