"""
AI-Generated Explanations for HITL Dialogs.

Part of AI-Native Enhancements for HITL Dialogs (Phase 1).

Provides AI-generated explanations for why an agent is uncertain,
what could go wrong, and safer alternatives. Replaces static templated
explanations with context-aware, LLM-generated content.

Architecture:
    ApprovalRequired → ExplanationOrchestrator → AIExplanation
                          ↓ (parallel)
    ┌─────────────────────────────────────────────────┐
    │ UncertaintyAgent  RiskAgent  AlternativesAgent  │
    │ EvidenceAgent (extracts confidence factors)     │
    └─────────────────────────────────────────────────┘

Models:
    - ExplanationType: Type of explanation (uncertainty, risk_analysis, etc.)
    - ConfidenceFactor: Individual factor affecting confidence score
    - AlternativeSuggestion: Safer alternative action with trade-offs
    - AIExplanation: Complete AI-generated explanation

Example:
    from mcp_server_langgraph.core.interrupts.ai_explanation import (
        AIExplanation,
        AlternativeSuggestion,
        ConfidenceFactor,
        ExplanationType,
    )

    explanation = AIExplanation(
        why_uncertain="The input contains ambiguous terms.",
        what_could_go_wrong="May perform unintended action.",
        safer_alternatives=[
            AlternativeSuggestion(
                action="Request clarification first",
                confidence=0.95,
                trade_off="Adds one extra interaction step",
            )
        ],
        confidence_factors=[
            ConfidenceFactor(
                factor="ambiguous_input",
                weight=-0.2,
                evidence="Query uses vague terms",
            )
        ],
    )
"""

from __future__ import annotations

from datetime import datetime, UTC
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ExplanationType(str, Enum):
    """Type of AI explanation.

    Categorizes the explanation to help UI rendering and analytics.

    Values:
        UNCERTAINTY: Explains why the agent lacks confidence
        RISK_ANALYSIS: Focuses on potential negative outcomes
        ALTERNATIVES: Emphasizes safer options
        EVIDENCE: Presents reasoning trace and confidence factors
    """

    UNCERTAINTY = "uncertainty"
    RISK_ANALYSIS = "risk_analysis"
    ALTERNATIVES = "alternatives"
    EVIDENCE = "evidence"


class ConfidenceFactor(BaseModel):
    """Individual factor contributing to confidence score.

    Represents a single piece of evidence that either increases or
    decreases the agent's confidence in its proposed action.

    Attributes:
        factor: Factor name (e.g., "ambiguous_input", "multiple_interpretations")
        weight: Impact on confidence (-1.0 to 1.0, negative reduces confidence)
        evidence: Supporting evidence or reasoning for this factor
    """

    factor: str = Field(description="Factor name identifying the confidence contributor")
    weight: float = Field(
        description="Impact on confidence score (-1.0 to 1.0)",
        ge=-1.0,
        le=1.0,
    )
    evidence: str = Field(description="Supporting evidence or reasoning for this factor")


class AlternativeSuggestion(BaseModel):
    """Safer alternative action the agent could take.

    Represents an alternative approach with expected confidence and
    trade-offs, helping users make informed decisions.

    Attributes:
        action: Description of the alternative action
        confidence: Expected confidence if this action is taken (0.0 to 1.0)
        trade_off: What the user gives up by choosing this alternative
    """

    action: str = Field(description="Description of the alternative action")
    confidence: float = Field(
        description="Expected confidence for this alternative (0.0 to 1.0)",
        ge=0.0,
        le=1.0,
    )
    trade_off: str = Field(description="Trade-off or limitation of this alternative")


class AIExplanation(BaseModel):
    """AI-generated explanation for HITL approval requests.

    Provides rich, context-aware explanations generated by the
    ExplanationOrchestrator using parallel analysis agents.

    Core Explanation:
        - why_uncertain: Natural language explanation of uncertainty
        - what_could_go_wrong: Risk analysis of potential issues
        - safer_alternatives: List of safer options with trade-offs

    Supporting Evidence:
        - confidence_factors: Factors affecting confidence score
        - reasoning_trace: Key steps in the agent's reasoning

    Metadata:
        - explanation_type: Category of explanation
        - model_used: LLM model that generated the explanation
        - generated_at: Timestamp of generation
        - generation_latency_ms: Time taken to generate
        - cached: Whether explanation was retrieved from cache

    Example:
        explanation = AIExplanation(
            why_uncertain="Multiple interpretations possible for 'delete old files'",
            what_could_go_wrong="May delete important files if threshold is wrong",
            safer_alternatives=[
                AlternativeSuggestion(
                    action="List files first, then confirm",
                    confidence=0.92,
                    trade_off="Extra step before deletion",
                )
            ],
            confidence_factors=[
                ConfidenceFactor(
                    factor="ambiguous_threshold",
                    weight=-0.25,
                    evidence="'Old' not defined precisely",
                )
            ],
        )
    """

    # Core explanation fields
    why_uncertain: str = Field(description="Natural language explanation of why the agent is uncertain")
    what_could_go_wrong: str = Field(description="Risk analysis of potential negative outcomes")

    # Optional lists (default to empty)
    safer_alternatives: list[AlternativeSuggestion] = Field(
        default_factory=list,
        description="List of safer alternative actions",
    )
    confidence_factors: list[ConfidenceFactor] = Field(
        default_factory=list,
        description="Factors affecting the confidence score",
    )
    reasoning_trace: list[str] = Field(
        default_factory=list,
        description="Key steps in the agent's reasoning process",
    )

    # Explanation metadata
    explanation_type: ExplanationType = Field(
        default=ExplanationType.UNCERTAINTY,
        description="Type of explanation for categorization",
    )
    model_used: str = Field(
        default="gpt-4o-mini",
        description="LLM model used to generate the explanation",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Timestamp when explanation was generated",
    )
    generation_latency_ms: float = Field(
        default=0.0,
        description="Time taken to generate explanation in milliseconds",
        ge=0.0,
    )
    cached: bool = Field(
        default=False,
        description="Whether explanation was retrieved from cache",
    )

    def to_frontend_dict(self) -> dict[str, Any]:
        """Convert to frontend-friendly dictionary.

        Serializes the explanation with ISO-formatted datetime for
        frontend consumption.

        Returns:
            Dict with all fields, datetime as ISO string
        """
        data = self.model_dump()
        data["generated_at"] = self.generated_at.isoformat()
        data["explanation_type"] = self.explanation_type.value
        return data
