# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class APIVersionInfo(BaseModel):
    """
    API version metadata  Follows semantic versioning (MAJOR.MINOR.PATCH): - MAJOR: Breaking changes (incompatible API changes) - MINOR: New features (backward-compatible) - PATCH: Bug fixes (backward-compatible)
    """  # noqa: E501

    version: StrictStr = Field(description="Application version (semantic versioning: MAJOR.MINOR.PATCH)")
    api_version: StrictStr = Field(description="Current API version (e.g., 'v1')")
    supported_versions: List[StrictStr] = Field(description="List of supported API versions")
    deprecated_versions: Optional[List[StrictStr]] = Field(
        default=None, description="List of deprecated API versions (still functional but will be removed)"
    )
    sunset_dates: Optional[Dict[str, StrictStr]] = Field(
        default=None, description="Sunset dates for deprecated versions (ISO 8601 format)"
    )
    changelog_url: Optional[StrictStr] = None
    documentation_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "version",
        "api_version",
        "supported_versions",
        "deprecated_versions",
        "sunset_dates",
        "changelog_url",
        "documentation_url",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIVersionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if changelog_url (nullable) is None
        # and model_fields_set contains the field
        if self.changelog_url is None and "changelog_url" in self.model_fields_set:
            _dict["changelog_url"] = None

        # set to None if documentation_url (nullable) is None
        # and model_fields_set contains the field
        if self.documentation_url is None and "documentation_url" in self.model_fields_set:
            _dict["documentation_url"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIVersionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "version": obj.get("version"),
                "api_version": obj.get("api_version"),
                "supported_versions": obj.get("supported_versions"),
                "deprecated_versions": obj.get("deprecated_versions"),
                "sunset_dates": obj.get("sunset_dates"),
                "changelog_url": obj.get("changelog_url"),
                "documentation_url": obj.get("documentation_url"),
            }
        )
        return _obj
