# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConsentType(str, Enum):
    """
    Types of consent that can be granted or revoked
    """

    """
    allowed enum values
    """
    ANALYTICS = 'analytics'
    MARKETING = 'marketing'
    THIRD_PARTY = 'third_party'
    PROFILING = 'profiling'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConsentType from a JSON string"""
        return cls(json.loads(json_str))


