# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class LoginResponse(BaseModel):
    """
    Login response with JWT token
    """  # noqa: E501

    access_token: StrictStr = Field(description="JWT access token")
    token_type: Optional[StrictStr] = Field(default="bearer", description="Token type (always 'bearer')")
    expires_in: StrictInt = Field(description="Token expiration in seconds")
    user_id: StrictStr = Field(description="User identifier")
    username: StrictStr = Field(description="Username")
    roles: List[StrictStr] = Field(description="User roles")
    __properties: ClassVar[List[str]] = ["access_token", "token_type", "expires_in", "user_id", "username", "roles"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoginResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoginResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "access_token": obj.get("access_token"),
                "token_type": obj.get("token_type") if obj.get("token_type") is not None else "bearer",
                "expires_in": obj.get("expires_in"),
                "user_id": obj.get("user_id"),
                "username": obj.get("username"),
                "roles": obj.get("roles"),
            }
        )
        return _obj
