# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mcp_client.models.scim_address import SCIMAddress
from mcp_client.models.scim_email import SCIMEmail
from mcp_client.models.scim_enterprise_user import SCIMEnterpriseUser
from mcp_client.models.scim_group_membership import SCIMGroupMembership
from mcp_client.models.scim_name import SCIMName
from mcp_client.models.scim_phone_number import SCIMPhoneNumber
from typing import Optional, Set
from typing_extensions import Self

class SCIMUser(BaseModel):
    """
    SCIM 2.0 User Resource  Core schema with optional Enterprise extension.
    """ # noqa: E501
    schemas: Optional[List[Optional[StrictStr]]] = None
    id: Optional[StrictStr] = None
    external_id: Optional[StrictStr] = Field(default=None, alias="externalId")
    user_name: StrictStr = Field(alias="userName")
    name: Optional[SCIMName] = None
    display_name: Optional[StrictStr] = Field(default=None, alias="displayName")
    nick_name: Optional[StrictStr] = Field(default=None, alias="nickName")
    profile_url: Optional[StrictStr] = Field(default=None, alias="profileUrl")
    title: Optional[StrictStr] = None
    user_type: Optional[StrictStr] = Field(default=None, alias="userType")
    preferred_language: Optional[StrictStr] = Field(default=None, alias="preferredLanguage")
    locale: Optional[StrictStr] = None
    timezone: Optional[StrictStr] = None
    active: Optional[StrictBool] = True
    password: Optional[StrictStr] = None
    emails: Optional[List[SCIMEmail]] = None
    phone_numbers: Optional[List[SCIMPhoneNumber]] = Field(default=None, alias="phoneNumbers")
    addresses: Optional[List[SCIMAddress]] = None
    groups: Optional[List[SCIMGroupMembership]] = None
    meta: Optional[Dict[str, Any]] = None
    urn_ietf_params_scim_schemas_extension_enterprise_2_0_user: Optional[SCIMEnterpriseUser] = Field(default=None, alias="urn:ietf:params:scim:schemas:extension:enterprise:2.0:User")
    __properties: ClassVar[List[str]] = ["schemas", "id", "externalId", "userName", "name", "displayName", "nickName", "profileUrl", "title", "userType", "preferredLanguage", "locale", "timezone", "active", "password", "emails", "phoneNumbers", "addresses", "groups", "meta", "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SCIMUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of name
        if self.name:
            _dict['name'] = self.name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in emails (list)
        _items = []
        if self.emails:
            for _item_emails in self.emails:
                if _item_emails:
                    _items.append(_item_emails.to_dict())
            _dict['emails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in phone_numbers (list)
        _items = []
        if self.phone_numbers:
            for _item_phone_numbers in self.phone_numbers:
                if _item_phone_numbers:
                    _items.append(_item_phone_numbers.to_dict())
            _dict['phoneNumbers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in addresses (list)
        _items = []
        if self.addresses:
            for _item_addresses in self.addresses:
                if _item_addresses:
                    _items.append(_item_addresses.to_dict())
            _dict['addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of urn_ietf_params_scim_schemas_extension_enterprise_2_0_user
        if self.urn_ietf_params_scim_schemas_extension_enterprise_2_0_user:
            _dict['urn:ietf:params:scim:schemas:extension:enterprise:2.0:User'] = self.urn_ietf_params_scim_schemas_extension_enterprise_2_0_user.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['externalId'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['displayName'] = None

        # set to None if nick_name (nullable) is None
        # and model_fields_set contains the field
        if self.nick_name is None and "nick_name" in self.model_fields_set:
            _dict['nickName'] = None

        # set to None if profile_url (nullable) is None
        # and model_fields_set contains the field
        if self.profile_url is None and "profile_url" in self.model_fields_set:
            _dict['profileUrl'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if user_type (nullable) is None
        # and model_fields_set contains the field
        if self.user_type is None and "user_type" in self.model_fields_set:
            _dict['userType'] = None

        # set to None if preferred_language (nullable) is None
        # and model_fields_set contains the field
        if self.preferred_language is None and "preferred_language" in self.model_fields_set:
            _dict['preferredLanguage'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if meta (nullable) is None
        # and model_fields_set contains the field
        if self.meta is None and "meta" in self.model_fields_set:
            _dict['meta'] = None

        # set to None if urn_ietf_params_scim_schemas_extension_enterprise_2_0_user (nullable) is None
        # and model_fields_set contains the field
        if self.urn_ietf_params_scim_schemas_extension_enterprise_2_0_user is None and "urn_ietf_params_scim_schemas_extension_enterprise_2_0_user" in self.model_fields_set:
            _dict['urn:ietf:params:scim:schemas:extension:enterprise:2.0:User'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SCIMUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schemas": obj.get("schemas"),
            "id": obj.get("id"),
            "externalId": obj.get("externalId"),
            "userName": obj.get("userName"),
            "name": SCIMName.from_dict(obj["name"]) if obj.get("name") is not None else None,
            "displayName": obj.get("displayName"),
            "nickName": obj.get("nickName"),
            "profileUrl": obj.get("profileUrl"),
            "title": obj.get("title"),
            "userType": obj.get("userType"),
            "preferredLanguage": obj.get("preferredLanguage"),
            "locale": obj.get("locale"),
            "timezone": obj.get("timezone"),
            "active": obj.get("active") if obj.get("active") is not None else True,
            "password": obj.get("password"),
            "emails": [SCIMEmail.from_dict(_item) for _item in obj["emails"]] if obj.get("emails") is not None else None,
            "phoneNumbers": [SCIMPhoneNumber.from_dict(_item) for _item in obj["phoneNumbers"]] if obj.get("phoneNumbers") is not None else None,
            "addresses": [SCIMAddress.from_dict(_item) for _item in obj["addresses"]] if obj.get("addresses") is not None else None,
            "groups": [SCIMGroupMembership.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "meta": obj.get("meta"),
            "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": SCIMEnterpriseUser.from_dict(obj["urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"]) if obj.get("urn:ietf:params:scim:schemas:extension:enterprise:2.0:User") is not None else None
        })
        return _obj


