# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SCIMEnterpriseUser(BaseModel):
    """
    SCIM Enterprise User Extension (RFC 7643 Section 4.3)
    """ # noqa: E501
    employee_number: Optional[StrictStr] = Field(default=None, alias="employeeNumber")
    cost_center: Optional[StrictStr] = Field(default=None, alias="costCenter")
    organization: Optional[StrictStr] = None
    division: Optional[StrictStr] = None
    department: Optional[StrictStr] = None
    manager: Optional[Dict[str, StrictStr]] = None
    __properties: ClassVar[List[str]] = ["employeeNumber", "costCenter", "organization", "division", "department", "manager"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SCIMEnterpriseUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if employee_number (nullable) is None
        # and model_fields_set contains the field
        if self.employee_number is None and "employee_number" in self.model_fields_set:
            _dict['employeeNumber'] = None

        # set to None if cost_center (nullable) is None
        # and model_fields_set contains the field
        if self.cost_center is None and "cost_center" in self.model_fields_set:
            _dict['costCenter'] = None

        # set to None if organization (nullable) is None
        # and model_fields_set contains the field
        if self.organization is None and "organization" in self.model_fields_set:
            _dict['organization'] = None

        # set to None if division (nullable) is None
        # and model_fields_set contains the field
        if self.division is None and "division" in self.model_fields_set:
            _dict['division'] = None

        # set to None if department (nullable) is None
        # and model_fields_set contains the field
        if self.department is None and "department" in self.model_fields_set:
            _dict['department'] = None

        # set to None if manager (nullable) is None
        # and model_fields_set contains the field
        if self.manager is None and "manager" in self.model_fields_set:
            _dict['manager'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SCIMEnterpriseUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "employeeNumber": obj.get("employeeNumber"),
            "costCenter": obj.get("costCenter"),
            "organization": obj.get("organization"),
            "division": obj.get("division"),
            "department": obj.get("department"),
            "manager": obj.get("manager")
        })
        return _obj


