# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServicePrincipalResponse(BaseModel):
    """
    Response containing service principal details
    """ # noqa: E501
    service_id: StrictStr
    name: StrictStr
    description: StrictStr
    authentication_mode: StrictStr
    associated_user_id: Optional[StrictStr]
    owner_user_id: Optional[StrictStr]
    inherit_permissions: StrictBool
    enabled: StrictBool
    created_at: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["service_id", "name", "description", "authentication_mode", "associated_user_id", "owner_user_id", "inherit_permissions", "enabled", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServicePrincipalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if associated_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.associated_user_id is None and "associated_user_id" in self.model_fields_set:
            _dict['associated_user_id'] = None

        # set to None if owner_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.owner_user_id is None and "owner_user_id" in self.model_fields_set:
            _dict['owner_user_id'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServicePrincipalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "service_id": obj.get("service_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "authentication_mode": obj.get("authentication_mode"),
            "associated_user_id": obj.get("associated_user_id"),
            "owner_user_id": obj.get("owner_user_id"),
            "inherit_permissions": obj.get("inherit_permissions"),
            "enabled": obj.get("enabled"),
            "created_at": obj.get("created_at")
        })
        return _obj


