"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class UserDataExport(BaseModel):
    """
    Complete user data export for GDPR compliance  Includes all personal data associated with a user.
    """  # noqa: E501

    export_id: StrictStr = Field(description="Unique export identifier")
    export_timestamp: StrictStr = Field(description="ISO timestamp of export")
    user_id: StrictStr = Field(description="User identifier")
    username: StrictStr = Field(description="Username")
    email: StrictStr = Field(description="User email address")
    profile: dict[str, Any] | None = Field(default=None, description="User profile data")
    sessions: list[dict[str, Any] | None] | None = Field(default=None, description="Active and recent sessions")
    conversations: list[dict[str, Any] | None] | None = Field(default=None, description="Conversation history")
    preferences: dict[str, Any] | None = Field(default=None, description="User preferences and settings")
    audit_log: list[dict[str, Any] | None] | None = Field(default=None, description="User activity audit log")
    consents: list[dict[str, Any] | None] | None = Field(default=None, description="Consent records")
    metadata: dict[str, Any] | None = Field(default=None, description="Additional metadata")
    __properties: ClassVar[list[str]] = [
        "export_id",
        "export_timestamp",
        "user_id",
        "username",
        "email",
        "profile",
        "sessions",
        "conversations",
        "preferences",
        "audit_log",
        "consents",
        "metadata",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of UserDataExport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of UserDataExport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "export_id": obj.get("export_id"),
                "export_timestamp": obj.get("export_timestamp"),
                "user_id": obj.get("user_id"),
                "username": obj.get("username"),
                "email": obj.get("email"),
                "profile": obj.get("profile"),
                "sessions": obj.get("sessions"),
                "conversations": obj.get("conversations"),
                "preferences": obj.get("preferences"),
                "audit_log": obj.get("audit_log"),
                "consents": obj.get("consents"),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
