/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HTTPAuthorizationCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HTTPAuthorizationCredentials{}

// HTTPAuthorizationCredentials The HTTP authorization credentials in the result of using `HTTPBearer` or `HTTPDigest` in a dependency.  The HTTP authorization header value is split by the first space.  The first part is the `scheme`, the second part is the `credentials`.  For example, in an HTTP Bearer token scheme, the client will send a header like:  ``` Authorization: Bearer deadbeef12346 ```  In this case:  * `scheme` will have the value `\"Bearer\"` * `credentials` will have the value `\"deadbeef12346\"`
type HTTPAuthorizationCredentials struct {
	Scheme string `json:"scheme"`
	Credentials string `json:"credentials"`
}

type _HTTPAuthorizationCredentials HTTPAuthorizationCredentials

// NewHTTPAuthorizationCredentials instantiates a new HTTPAuthorizationCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHTTPAuthorizationCredentials(scheme string, credentials string) *HTTPAuthorizationCredentials {
	this := HTTPAuthorizationCredentials{}
	this.Scheme = scheme
	this.Credentials = credentials
	return &this
}

// NewHTTPAuthorizationCredentialsWithDefaults instantiates a new HTTPAuthorizationCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHTTPAuthorizationCredentialsWithDefaults() *HTTPAuthorizationCredentials {
	this := HTTPAuthorizationCredentials{}
	return &this
}

// GetScheme returns the Scheme field value
func (o *HTTPAuthorizationCredentials) GetScheme() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value
// and a boolean to check if the value has been set.
func (o *HTTPAuthorizationCredentials) GetSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scheme, true
}

// SetScheme sets field value
func (o *HTTPAuthorizationCredentials) SetScheme(v string) {
	o.Scheme = v
}

// GetCredentials returns the Credentials field value
func (o *HTTPAuthorizationCredentials) GetCredentials() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *HTTPAuthorizationCredentials) GetCredentialsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *HTTPAuthorizationCredentials) SetCredentials(v string) {
	o.Credentials = v
}

func (o HTTPAuthorizationCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HTTPAuthorizationCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scheme"] = o.Scheme
	toSerialize["credentials"] = o.Credentials
	return toSerialize, nil
}

func (o *HTTPAuthorizationCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scheme",
		"credentials",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHTTPAuthorizationCredentials := _HTTPAuthorizationCredentials{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHTTPAuthorizationCredentials)

	if err != nil {
		return err
	}

	*o = HTTPAuthorizationCredentials(varHTTPAuthorizationCredentials)

	return err
}

type NullableHTTPAuthorizationCredentials struct {
	value *HTTPAuthorizationCredentials
	isSet bool
}

func (v NullableHTTPAuthorizationCredentials) Get() *HTTPAuthorizationCredentials {
	return v.value
}

func (v *NullableHTTPAuthorizationCredentials) Set(val *HTTPAuthorizationCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableHTTPAuthorizationCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableHTTPAuthorizationCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHTTPAuthorizationCredentials(val *HTTPAuthorizationCredentials) *NullableHTTPAuthorizationCredentials {
	return &NullableHTTPAuthorizationCredentials{value: val, isSet: true}
}

func (v NullableHTTPAuthorizationCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHTTPAuthorizationCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


