/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyUpdateUserProfileApiV1UsersMePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyUpdateUserProfileApiV1UsersMePatch{}

// BodyUpdateUserProfileApiV1UsersMePatch struct for BodyUpdateUserProfileApiV1UsersMePatch
type BodyUpdateUserProfileApiV1UsersMePatch struct {
	ProfileUpdate UserProfileUpdate `json:"profile_update"`
	Credentials NullableHTTPAuthorizationCredentials `json:"credentials,omitempty"`
}

type _BodyUpdateUserProfileApiV1UsersMePatch BodyUpdateUserProfileApiV1UsersMePatch

// NewBodyUpdateUserProfileApiV1UsersMePatch instantiates a new BodyUpdateUserProfileApiV1UsersMePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyUpdateUserProfileApiV1UsersMePatch(profileUpdate UserProfileUpdate) *BodyUpdateUserProfileApiV1UsersMePatch {
	this := BodyUpdateUserProfileApiV1UsersMePatch{}
	this.ProfileUpdate = profileUpdate
	return &this
}

// NewBodyUpdateUserProfileApiV1UsersMePatchWithDefaults instantiates a new BodyUpdateUserProfileApiV1UsersMePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyUpdateUserProfileApiV1UsersMePatchWithDefaults() *BodyUpdateUserProfileApiV1UsersMePatch {
	this := BodyUpdateUserProfileApiV1UsersMePatch{}
	return &this
}

// GetProfileUpdate returns the ProfileUpdate field value
func (o *BodyUpdateUserProfileApiV1UsersMePatch) GetProfileUpdate() UserProfileUpdate {
	if o == nil {
		var ret UserProfileUpdate
		return ret
	}

	return o.ProfileUpdate
}

// GetProfileUpdateOk returns a tuple with the ProfileUpdate field value
// and a boolean to check if the value has been set.
func (o *BodyUpdateUserProfileApiV1UsersMePatch) GetProfileUpdateOk() (*UserProfileUpdate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileUpdate, true
}

// SetProfileUpdate sets field value
func (o *BodyUpdateUserProfileApiV1UsersMePatch) SetProfileUpdate(v UserProfileUpdate) {
	o.ProfileUpdate = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BodyUpdateUserProfileApiV1UsersMePatch) GetCredentials() HTTPAuthorizationCredentials {
	if o == nil || IsNil(o.Credentials.Get()) {
		var ret HTTPAuthorizationCredentials
		return ret
	}
	return *o.Credentials.Get()
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BodyUpdateUserProfileApiV1UsersMePatch) GetCredentialsOk() (*HTTPAuthorizationCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credentials.Get(), o.Credentials.IsSet()
}

// HasCredentials returns a boolean if a field has been set.
func (o *BodyUpdateUserProfileApiV1UsersMePatch) HasCredentials() bool {
	if o != nil && o.Credentials.IsSet() {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given NullableHTTPAuthorizationCredentials and assigns it to the Credentials field.
func (o *BodyUpdateUserProfileApiV1UsersMePatch) SetCredentials(v HTTPAuthorizationCredentials) {
	o.Credentials.Set(&v)
}
// SetCredentialsNil sets the value for Credentials to be an explicit nil
func (o *BodyUpdateUserProfileApiV1UsersMePatch) SetCredentialsNil() {
	o.Credentials.Set(nil)
}

// UnsetCredentials ensures that no value is present for Credentials, not even an explicit nil
func (o *BodyUpdateUserProfileApiV1UsersMePatch) UnsetCredentials() {
	o.Credentials.Unset()
}

func (o BodyUpdateUserProfileApiV1UsersMePatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyUpdateUserProfileApiV1UsersMePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["profile_update"] = o.ProfileUpdate
	if o.Credentials.IsSet() {
		toSerialize["credentials"] = o.Credentials.Get()
	}
	return toSerialize, nil
}

func (o *BodyUpdateUserProfileApiV1UsersMePatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"profile_update",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyUpdateUserProfileApiV1UsersMePatch := _BodyUpdateUserProfileApiV1UsersMePatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyUpdateUserProfileApiV1UsersMePatch)

	if err != nil {
		return err
	}

	*o = BodyUpdateUserProfileApiV1UsersMePatch(varBodyUpdateUserProfileApiV1UsersMePatch)

	return err
}

type NullableBodyUpdateUserProfileApiV1UsersMePatch struct {
	value *BodyUpdateUserProfileApiV1UsersMePatch
	isSet bool
}

func (v NullableBodyUpdateUserProfileApiV1UsersMePatch) Get() *BodyUpdateUserProfileApiV1UsersMePatch {
	return v.value
}

func (v *NullableBodyUpdateUserProfileApiV1UsersMePatch) Set(val *BodyUpdateUserProfileApiV1UsersMePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyUpdateUserProfileApiV1UsersMePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyUpdateUserProfileApiV1UsersMePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyUpdateUserProfileApiV1UsersMePatch(val *BodyUpdateUserProfileApiV1UsersMePatch) *NullableBodyUpdateUserProfileApiV1UsersMePatch {
	return &NullableBodyUpdateUserProfileApiV1UsersMePatch{value: val, isSet: true}
}

func (v NullableBodyUpdateUserProfileApiV1UsersMePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyUpdateUserProfileApiV1UsersMePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
