/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the APIVersionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIVersionInfo{}

// APIVersionInfo API version metadata  Follows semantic versioning (MAJOR.MINOR.PATCH): - MAJOR: Breaking changes (incompatible API changes) - MINOR: New features (backward-compatible) - PATCH: Bug fixes (backward-compatible)
type APIVersionInfo struct {
	// Application version (semantic versioning: MAJOR.MINOR.PATCH)
	Version string `json:"version"`
	// Current API version (e.g., 'v1')
	ApiVersion string `json:"api_version"`
	// List of supported API versions
	SupportedVersions []string `json:"supported_versions"`
	// List of deprecated API versions (still functional but will be removed)
	DeprecatedVersions []string `json:"deprecated_versions,omitempty"`
	// Sunset dates for deprecated versions (ISO 8601 format)
	SunsetDates map[string]string `json:"sunset_dates,omitempty"`
	ChangelogUrl NullableString `json:"changelog_url,omitempty"`
	DocumentationUrl NullableString `json:"documentation_url,omitempty"`
}

type _APIVersionInfo APIVersionInfo

// NewAPIVersionInfo instantiates a new APIVersionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIVersionInfo(version string, apiVersion string, supportedVersions []string) *APIVersionInfo {
	this := APIVersionInfo{}
	this.Version = version
	this.ApiVersion = apiVersion
	this.SupportedVersions = supportedVersions
	return &this
}

// NewAPIVersionInfoWithDefaults instantiates a new APIVersionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIVersionInfoWithDefaults() *APIVersionInfo {
	this := APIVersionInfo{}
	return &this
}

// GetVersion returns the Version field value
func (o *APIVersionInfo) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *APIVersionInfo) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *APIVersionInfo) SetVersion(v string) {
	o.Version = v
}

// GetApiVersion returns the ApiVersion field value
func (o *APIVersionInfo) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *APIVersionInfo) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *APIVersionInfo) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetSupportedVersions returns the SupportedVersions field value
func (o *APIVersionInfo) GetSupportedVersions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SupportedVersions
}

// GetSupportedVersionsOk returns a tuple with the SupportedVersions field value
// and a boolean to check if the value has been set.
func (o *APIVersionInfo) GetSupportedVersionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedVersions, true
}

// SetSupportedVersions sets field value
func (o *APIVersionInfo) SetSupportedVersions(v []string) {
	o.SupportedVersions = v
}

// GetDeprecatedVersions returns the DeprecatedVersions field value if set, zero value otherwise.
func (o *APIVersionInfo) GetDeprecatedVersions() []string {
	if o == nil || IsNil(o.DeprecatedVersions) {
		var ret []string
		return ret
	}
	return o.DeprecatedVersions
}

// GetDeprecatedVersionsOk returns a tuple with the DeprecatedVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIVersionInfo) GetDeprecatedVersionsOk() ([]string, bool) {
	if o == nil || IsNil(o.DeprecatedVersions) {
		return nil, false
	}
	return o.DeprecatedVersions, true
}

// HasDeprecatedVersions returns a boolean if a field has been set.
func (o *APIVersionInfo) HasDeprecatedVersions() bool {
	if o != nil && !IsNil(o.DeprecatedVersions) {
		return true
	}

	return false
}

// SetDeprecatedVersions gets a reference to the given []string and assigns it to the DeprecatedVersions field.
func (o *APIVersionInfo) SetDeprecatedVersions(v []string) {
	o.DeprecatedVersions = v
}

// GetSunsetDates returns the SunsetDates field value if set, zero value otherwise.
func (o *APIVersionInfo) GetSunsetDates() map[string]string {
	if o == nil || IsNil(o.SunsetDates) {
		var ret map[string]string
		return ret
	}
	return o.SunsetDates
}

// GetSunsetDatesOk returns a tuple with the SunsetDates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIVersionInfo) GetSunsetDatesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.SunsetDates) {
		return map[string]string{}, false
	}
	return o.SunsetDates, true
}

// HasSunsetDates returns a boolean if a field has been set.
func (o *APIVersionInfo) HasSunsetDates() bool {
	if o != nil && !IsNil(o.SunsetDates) {
		return true
	}

	return false
}

// SetSunsetDates gets a reference to the given map[string]string and assigns it to the SunsetDates field.
func (o *APIVersionInfo) SetSunsetDates(v map[string]string) {
	o.SunsetDates = v
}

// GetChangelogUrl returns the ChangelogUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *APIVersionInfo) GetChangelogUrl() string {
	if o == nil || IsNil(o.ChangelogUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ChangelogUrl.Get()
}

// GetChangelogUrlOk returns a tuple with the ChangelogUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *APIVersionInfo) GetChangelogUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangelogUrl.Get(), o.ChangelogUrl.IsSet()
}

// HasChangelogUrl returns a boolean if a field has been set.
func (o *APIVersionInfo) HasChangelogUrl() bool {
	if o != nil && o.ChangelogUrl.IsSet() {
		return true
	}

	return false
}

// SetChangelogUrl gets a reference to the given NullableString and assigns it to the ChangelogUrl field.
func (o *APIVersionInfo) SetChangelogUrl(v string) {
	o.ChangelogUrl.Set(&v)
}
// SetChangelogUrlNil sets the value for ChangelogUrl to be an explicit nil
func (o *APIVersionInfo) SetChangelogUrlNil() {
	o.ChangelogUrl.Set(nil)
}

// UnsetChangelogUrl ensures that no value is present for ChangelogUrl, not even an explicit nil
func (o *APIVersionInfo) UnsetChangelogUrl() {
	o.ChangelogUrl.Unset()
}

// GetDocumentationUrl returns the DocumentationUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *APIVersionInfo) GetDocumentationUrl() string {
	if o == nil || IsNil(o.DocumentationUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentationUrl.Get()
}

// GetDocumentationUrlOk returns a tuple with the DocumentationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *APIVersionInfo) GetDocumentationUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentationUrl.Get(), o.DocumentationUrl.IsSet()
}

// HasDocumentationUrl returns a boolean if a field has been set.
func (o *APIVersionInfo) HasDocumentationUrl() bool {
	if o != nil && o.DocumentationUrl.IsSet() {
		return true
	}

	return false
}

// SetDocumentationUrl gets a reference to the given NullableString and assigns it to the DocumentationUrl field.
func (o *APIVersionInfo) SetDocumentationUrl(v string) {
	o.DocumentationUrl.Set(&v)
}
// SetDocumentationUrlNil sets the value for DocumentationUrl to be an explicit nil
func (o *APIVersionInfo) SetDocumentationUrlNil() {
	o.DocumentationUrl.Set(nil)
}

// UnsetDocumentationUrl ensures that no value is present for DocumentationUrl, not even an explicit nil
func (o *APIVersionInfo) UnsetDocumentationUrl() {
	o.DocumentationUrl.Unset()
}

func (o APIVersionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIVersionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["api_version"] = o.ApiVersion
	toSerialize["supported_versions"] = o.SupportedVersions
	if !IsNil(o.DeprecatedVersions) {
		toSerialize["deprecated_versions"] = o.DeprecatedVersions
	}
	if !IsNil(o.SunsetDates) {
		toSerialize["sunset_dates"] = o.SunsetDates
	}
	if o.ChangelogUrl.IsSet() {
		toSerialize["changelog_url"] = o.ChangelogUrl.Get()
	}
	if o.DocumentationUrl.IsSet() {
		toSerialize["documentation_url"] = o.DocumentationUrl.Get()
	}
	return toSerialize, nil
}

func (o *APIVersionInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"api_version",
		"supported_versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIVersionInfo := _APIVersionInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIVersionInfo)

	if err != nil {
		return err
	}

	*o = APIVersionInfo(varAPIVersionInfo)

	return err
}

type NullableAPIVersionInfo struct {
	value *APIVersionInfo
	isSet bool
}

func (v NullableAPIVersionInfo) Get() *APIVersionInfo {
	return v.value
}

func (v *NullableAPIVersionInfo) Set(val *APIVersionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIVersionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIVersionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIVersionInfo(val *APIVersionInfo) *NullableAPIVersionInfo {
	return &NullableAPIVersionInfo{value: val, isSet: true}
}

func (v NullableAPIVersionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIVersionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


