/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateServicePrincipalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateServicePrincipalResponse{}

// CreateServicePrincipalResponse Response when creating service principal (includes secret)
type CreateServicePrincipalResponse struct {
	ServiceId string `json:"service_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	AuthenticationMode string `json:"authentication_mode"`
	AssociatedUserId NullableString `json:"associated_user_id"`
	OwnerUserId NullableString `json:"owner_user_id"`
	InheritPermissions bool `json:"inherit_permissions"`
	Enabled bool `json:"enabled"`
	CreatedAt NullableString `json:"created_at"`
	// Client secret (save securely, won't be shown again)
	ClientSecret string `json:"client_secret"`
	Message *string `json:"message,omitempty"`
}

type _CreateServicePrincipalResponse CreateServicePrincipalResponse

// NewCreateServicePrincipalResponse instantiates a new CreateServicePrincipalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateServicePrincipalResponse(serviceId string, name string, description string, authenticationMode string, associatedUserId NullableString, ownerUserId NullableString, inheritPermissions bool, enabled bool, createdAt NullableString, clientSecret string) *CreateServicePrincipalResponse {
	this := CreateServicePrincipalResponse{}
	this.ServiceId = serviceId
	this.Name = name
	this.Description = description
	this.AuthenticationMode = authenticationMode
	this.AssociatedUserId = associatedUserId
	this.OwnerUserId = ownerUserId
	this.InheritPermissions = inheritPermissions
	this.Enabled = enabled
	this.CreatedAt = createdAt
	this.ClientSecret = clientSecret
	var message string = "Service principal created successfully. Save the client_secret securely."
	this.Message = &message
	return &this
}

// NewCreateServicePrincipalResponseWithDefaults instantiates a new CreateServicePrincipalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateServicePrincipalResponseWithDefaults() *CreateServicePrincipalResponse {
	this := CreateServicePrincipalResponse{}
	var message string = "Service principal created successfully. Save the client_secret securely."
	this.Message = &message
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *CreateServicePrincipalResponse) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *CreateServicePrincipalResponse) SetServiceId(v string) {
	o.ServiceId = v
}

// GetName returns the Name field value
func (o *CreateServicePrincipalResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateServicePrincipalResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreateServicePrincipalResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateServicePrincipalResponse) SetDescription(v string) {
	o.Description = v
}

// GetAuthenticationMode returns the AuthenticationMode field value
func (o *CreateServicePrincipalResponse) GetAuthenticationMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationMode
}

// GetAuthenticationModeOk returns a tuple with the AuthenticationMode field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetAuthenticationModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationMode, true
}

// SetAuthenticationMode sets field value
func (o *CreateServicePrincipalResponse) SetAuthenticationMode(v string) {
	o.AuthenticationMode = v
}

// GetAssociatedUserId returns the AssociatedUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateServicePrincipalResponse) GetAssociatedUserId() string {
	if o == nil || o.AssociatedUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.AssociatedUserId.Get()
}

// GetAssociatedUserIdOk returns a tuple with the AssociatedUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateServicePrincipalResponse) GetAssociatedUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssociatedUserId.Get(), o.AssociatedUserId.IsSet()
}

// SetAssociatedUserId sets field value
func (o *CreateServicePrincipalResponse) SetAssociatedUserId(v string) {
	o.AssociatedUserId.Set(&v)
}

// GetOwnerUserId returns the OwnerUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateServicePrincipalResponse) GetOwnerUserId() string {
	if o == nil || o.OwnerUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OwnerUserId.Get()
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateServicePrincipalResponse) GetOwnerUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerUserId.Get(), o.OwnerUserId.IsSet()
}

// SetOwnerUserId sets field value
func (o *CreateServicePrincipalResponse) SetOwnerUserId(v string) {
	o.OwnerUserId.Set(&v)
}

// GetInheritPermissions returns the InheritPermissions field value
func (o *CreateServicePrincipalResponse) GetInheritPermissions() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InheritPermissions
}

// GetInheritPermissionsOk returns a tuple with the InheritPermissions field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetInheritPermissionsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InheritPermissions, true
}

// SetInheritPermissions sets field value
func (o *CreateServicePrincipalResponse) SetInheritPermissions(v bool) {
	o.InheritPermissions = v
}

// GetEnabled returns the Enabled field value
func (o *CreateServicePrincipalResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CreateServicePrincipalResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateServicePrincipalResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateServicePrincipalResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *CreateServicePrincipalResponse) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// GetClientSecret returns the ClientSecret field value
func (o *CreateServicePrincipalResponse) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *CreateServicePrincipalResponse) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateServicePrincipalResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateServicePrincipalResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateServicePrincipalResponse) SetMessage(v string) {
	o.Message = &v
}

func (o CreateServicePrincipalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateServicePrincipalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["authentication_mode"] = o.AuthenticationMode
	toSerialize["associated_user_id"] = o.AssociatedUserId.Get()
	toSerialize["owner_user_id"] = o.OwnerUserId.Get()
	toSerialize["inherit_permissions"] = o.InheritPermissions
	toSerialize["enabled"] = o.Enabled
	toSerialize["created_at"] = o.CreatedAt.Get()
	toSerialize["client_secret"] = o.ClientSecret
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *CreateServicePrincipalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"name",
		"description",
		"authentication_mode",
		"associated_user_id",
		"owner_user_id",
		"inherit_permissions",
		"enabled",
		"created_at",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateServicePrincipalResponse := _CreateServicePrincipalResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateServicePrincipalResponse)

	if err != nil {
		return err
	}

	*o = CreateServicePrincipalResponse(varCreateServicePrincipalResponse)

	return err
}

type NullableCreateServicePrincipalResponse struct {
	value *CreateServicePrincipalResponse
	isSet bool
}

func (v NullableCreateServicePrincipalResponse) Get() *CreateServicePrincipalResponse {
	return v.value
}

func (v *NullableCreateServicePrincipalResponse) Set(val *CreateServicePrincipalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateServicePrincipalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateServicePrincipalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateServicePrincipalResponse(val *CreateServicePrincipalResponse) *NullableCreateServicePrincipalResponse {
	return &NullableCreateServicePrincipalResponse{value: val, isSet: true}
}

func (v NullableCreateServicePrincipalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateServicePrincipalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
