/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SCIMMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCIMMember{}

// SCIMMember SCIM group member
type SCIMMember struct {
	Value string `json:"value"`
	Ref NullableString `json:"ref,omitempty"`
	Display NullableString `json:"display,omitempty"`
	Type NullableString `json:"type,omitempty"`
}

type _SCIMMember SCIMMember

// NewSCIMMember instantiates a new SCIMMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCIMMember(value string) *SCIMMember {
	this := SCIMMember{}
	this.Value = value
	return &this
}

// NewSCIMMemberWithDefaults instantiates a new SCIMMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCIMMemberWithDefaults() *SCIMMember {
	this := SCIMMember{}
	return &this
}

// GetValue returns the Value field value
func (o *SCIMMember) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SCIMMember) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SCIMMember) SetValue(v string) {
	o.Value = v
}

// GetRef returns the Ref field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMMember) GetRef() string {
	if o == nil || IsNil(o.Ref.Get()) {
		var ret string
		return ret
	}
	return *o.Ref.Get()
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMMember) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ref.Get(), o.Ref.IsSet()
}

// HasRef returns a boolean if a field has been set.
func (o *SCIMMember) HasRef() bool {
	if o != nil && o.Ref.IsSet() {
		return true
	}

	return false
}

// SetRef gets a reference to the given NullableString and assigns it to the Ref field.
func (o *SCIMMember) SetRef(v string) {
	o.Ref.Set(&v)
}
// SetRefNil sets the value for Ref to be an explicit nil
func (o *SCIMMember) SetRefNil() {
	o.Ref.Set(nil)
}

// UnsetRef ensures that no value is present for Ref, not even an explicit nil
func (o *SCIMMember) UnsetRef() {
	o.Ref.Unset()
}

// GetDisplay returns the Display field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMMember) GetDisplay() string {
	if o == nil || IsNil(o.Display.Get()) {
		var ret string
		return ret
	}
	return *o.Display.Get()
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMMember) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Display.Get(), o.Display.IsSet()
}

// HasDisplay returns a boolean if a field has been set.
func (o *SCIMMember) HasDisplay() bool {
	if o != nil && o.Display.IsSet() {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given NullableString and assigns it to the Display field.
func (o *SCIMMember) SetDisplay(v string) {
	o.Display.Set(&v)
}
// SetDisplayNil sets the value for Display to be an explicit nil
func (o *SCIMMember) SetDisplayNil() {
	o.Display.Set(nil)
}

// UnsetDisplay ensures that no value is present for Display, not even an explicit nil
func (o *SCIMMember) UnsetDisplay() {
	o.Display.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMMember) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMMember) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *SCIMMember) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *SCIMMember) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *SCIMMember) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *SCIMMember) UnsetType() {
	o.Type.Unset()
}

func (o SCIMMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCIMMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	if o.Ref.IsSet() {
		toSerialize["ref"] = o.Ref.Get()
	}
	if o.Display.IsSet() {
		toSerialize["display"] = o.Display.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	return toSerialize, nil
}

func (o *SCIMMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSCIMMember := _SCIMMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSCIMMember)

	if err != nil {
		return err
	}

	*o = SCIMMember(varSCIMMember)

	return err
}

type NullableSCIMMember struct {
	value *SCIMMember
	isSet bool
}

func (v NullableSCIMMember) Get() *SCIMMember {
	return v.value
}

func (v *NullableSCIMMember) Set(val *SCIMMember) {
	v.value = val
	v.isSet = true
}

func (v NullableSCIMMember) IsSet() bool {
	return v.isSet
}

func (v *NullableSCIMMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCIMMember(val *SCIMMember) *NullableSCIMMember {
	return &NullableSCIMMember{value: val, isSet: true}
}

func (v NullableSCIMMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCIMMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


