/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SCIMUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCIMUser{}

// SCIMUser SCIM 2.0 User Resource  Core schema with optional Enterprise extension.
type SCIMUser struct {
	Schemas []*string `json:"schemas,omitempty"`
	Id NullableString `json:"id,omitempty"`
	ExternalId NullableString `json:"externalId,omitempty"`
	UserName string `json:"userName"`
	Name NullableSCIMName `json:"name,omitempty"`
	DisplayName NullableString `json:"displayName,omitempty"`
	NickName NullableString `json:"nickName,omitempty"`
	ProfileUrl NullableString `json:"profileUrl,omitempty"`
	Title NullableString `json:"title,omitempty"`
	UserType NullableString `json:"userType,omitempty"`
	PreferredLanguage NullableString `json:"preferredLanguage,omitempty"`
	Locale NullableString `json:"locale,omitempty"`
	Timezone NullableString `json:"timezone,omitempty"`
	Active *bool `json:"active,omitempty"`
	Password NullableString `json:"password,omitempty"`
	Emails []SCIMEmail `json:"emails,omitempty"`
	PhoneNumbers []SCIMPhoneNumber `json:"phoneNumbers,omitempty"`
	Addresses []SCIMAddress `json:"addresses,omitempty"`
	Groups []SCIMGroupMembership `json:"groups,omitempty"`
	Meta map[string]interface{} `json:"meta,omitempty"`
	UrnIetfParamsScimSchemasExtensionEnterprise20User NullableSCIMEnterpriseUser `json:"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User,omitempty"`
}

type _SCIMUser SCIMUser

// NewSCIMUser instantiates a new SCIMUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCIMUser(userName string) *SCIMUser {
	this := SCIMUser{}
	this.UserName = userName
	var active bool = true
	this.Active = &active
	return &this
}

// NewSCIMUserWithDefaults instantiates a new SCIMUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCIMUserWithDefaults() *SCIMUser {
	this := SCIMUser{}
	var active bool = true
	this.Active = &active
	return &this
}

// GetSchemas returns the Schemas field value if set, zero value otherwise.
func (o *SCIMUser) GetSchemas() []*string {
	if o == nil || IsNil(o.Schemas) {
		var ret []*string
		return ret
	}
	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetSchemasOk() ([]*string, bool) {
	if o == nil || IsNil(o.Schemas) {
		return nil, false
	}
	return o.Schemas, true
}

// HasSchemas returns a boolean if a field has been set.
func (o *SCIMUser) HasSchemas() bool {
	if o != nil && !IsNil(o.Schemas) {
		return true
	}

	return false
}

// SetSchemas gets a reference to the given []*string and assigns it to the Schemas field.
func (o *SCIMUser) SetSchemas(v []*string) {
	o.Schemas = v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *SCIMUser) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *SCIMUser) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *SCIMUser) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *SCIMUser) UnsetId() {
	o.Id.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *SCIMUser) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *SCIMUser) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}
// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *SCIMUser) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *SCIMUser) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetUserName returns the UserName field value
func (o *SCIMUser) GetUserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserName, true
}

// SetUserName sets field value
func (o *SCIMUser) SetUserName(v string) {
	o.UserName = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetName() SCIMName {
	if o == nil || IsNil(o.Name.Get()) {
		var ret SCIMName
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetNameOk() (*SCIMName, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *SCIMUser) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableSCIMName and assigns it to the Name field.
func (o *SCIMUser) SetName(v SCIMName) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *SCIMUser) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *SCIMUser) UnsetName() {
	o.Name.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *SCIMUser) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *SCIMUser) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *SCIMUser) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *SCIMUser) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetNickName returns the NickName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetNickName() string {
	if o == nil || IsNil(o.NickName.Get()) {
		var ret string
		return ret
	}
	return *o.NickName.Get()
}

// GetNickNameOk returns a tuple with the NickName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetNickNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NickName.Get(), o.NickName.IsSet()
}

// HasNickName returns a boolean if a field has been set.
func (o *SCIMUser) HasNickName() bool {
	if o != nil && o.NickName.IsSet() {
		return true
	}

	return false
}

// SetNickName gets a reference to the given NullableString and assigns it to the NickName field.
func (o *SCIMUser) SetNickName(v string) {
	o.NickName.Set(&v)
}
// SetNickNameNil sets the value for NickName to be an explicit nil
func (o *SCIMUser) SetNickNameNil() {
	o.NickName.Set(nil)
}

// UnsetNickName ensures that no value is present for NickName, not even an explicit nil
func (o *SCIMUser) UnsetNickName() {
	o.NickName.Unset()
}

// GetProfileUrl returns the ProfileUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetProfileUrl() string {
	if o == nil || IsNil(o.ProfileUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ProfileUrl.Get()
}

// GetProfileUrlOk returns a tuple with the ProfileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetProfileUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileUrl.Get(), o.ProfileUrl.IsSet()
}

// HasProfileUrl returns a boolean if a field has been set.
func (o *SCIMUser) HasProfileUrl() bool {
	if o != nil && o.ProfileUrl.IsSet() {
		return true
	}

	return false
}

// SetProfileUrl gets a reference to the given NullableString and assigns it to the ProfileUrl field.
func (o *SCIMUser) SetProfileUrl(v string) {
	o.ProfileUrl.Set(&v)
}
// SetProfileUrlNil sets the value for ProfileUrl to be an explicit nil
func (o *SCIMUser) SetProfileUrlNil() {
	o.ProfileUrl.Set(nil)
}

// UnsetProfileUrl ensures that no value is present for ProfileUrl, not even an explicit nil
func (o *SCIMUser) UnsetProfileUrl() {
	o.ProfileUrl.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *SCIMUser) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *SCIMUser) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *SCIMUser) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *SCIMUser) UnsetTitle() {
	o.Title.Unset()
}

// GetUserType returns the UserType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetUserType() string {
	if o == nil || IsNil(o.UserType.Get()) {
		var ret string
		return ret
	}
	return *o.UserType.Get()
}

// GetUserTypeOk returns a tuple with the UserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetUserTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserType.Get(), o.UserType.IsSet()
}

// HasUserType returns a boolean if a field has been set.
func (o *SCIMUser) HasUserType() bool {
	if o != nil && o.UserType.IsSet() {
		return true
	}

	return false
}

// SetUserType gets a reference to the given NullableString and assigns it to the UserType field.
func (o *SCIMUser) SetUserType(v string) {
	o.UserType.Set(&v)
}
// SetUserTypeNil sets the value for UserType to be an explicit nil
func (o *SCIMUser) SetUserTypeNil() {
	o.UserType.Set(nil)
}

// UnsetUserType ensures that no value is present for UserType, not even an explicit nil
func (o *SCIMUser) UnsetUserType() {
	o.UserType.Unset()
}

// GetPreferredLanguage returns the PreferredLanguage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetPreferredLanguage() string {
	if o == nil || IsNil(o.PreferredLanguage.Get()) {
		var ret string
		return ret
	}
	return *o.PreferredLanguage.Get()
}

// GetPreferredLanguageOk returns a tuple with the PreferredLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetPreferredLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreferredLanguage.Get(), o.PreferredLanguage.IsSet()
}

// HasPreferredLanguage returns a boolean if a field has been set.
func (o *SCIMUser) HasPreferredLanguage() bool {
	if o != nil && o.PreferredLanguage.IsSet() {
		return true
	}

	return false
}

// SetPreferredLanguage gets a reference to the given NullableString and assigns it to the PreferredLanguage field.
func (o *SCIMUser) SetPreferredLanguage(v string) {
	o.PreferredLanguage.Set(&v)
}
// SetPreferredLanguageNil sets the value for PreferredLanguage to be an explicit nil
func (o *SCIMUser) SetPreferredLanguageNil() {
	o.PreferredLanguage.Set(nil)
}

// UnsetPreferredLanguage ensures that no value is present for PreferredLanguage, not even an explicit nil
func (o *SCIMUser) UnsetPreferredLanguage() {
	o.PreferredLanguage.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *SCIMUser) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *SCIMUser) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *SCIMUser) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *SCIMUser) UnsetLocale() {
	o.Locale.Unset()
}

// GetTimezone returns the Timezone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetTimezone() string {
	if o == nil || IsNil(o.Timezone.Get()) {
		var ret string
		return ret
	}
	return *o.Timezone.Get()
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timezone.Get(), o.Timezone.IsSet()
}

// HasTimezone returns a boolean if a field has been set.
func (o *SCIMUser) HasTimezone() bool {
	if o != nil && o.Timezone.IsSet() {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given NullableString and assigns it to the Timezone field.
func (o *SCIMUser) SetTimezone(v string) {
	o.Timezone.Set(&v)
}
// SetTimezoneNil sets the value for Timezone to be an explicit nil
func (o *SCIMUser) SetTimezoneNil() {
	o.Timezone.Set(nil)
}

// UnsetTimezone ensures that no value is present for Timezone, not even an explicit nil
func (o *SCIMUser) UnsetTimezone() {
	o.Timezone.Unset()
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *SCIMUser) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *SCIMUser) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *SCIMUser) SetActive(v bool) {
	o.Active = &v
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *SCIMUser) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *SCIMUser) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *SCIMUser) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *SCIMUser) UnsetPassword() {
	o.Password.Unset()
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *SCIMUser) GetEmails() []SCIMEmail {
	if o == nil || IsNil(o.Emails) {
		var ret []SCIMEmail
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetEmailsOk() ([]SCIMEmail, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *SCIMUser) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []SCIMEmail and assigns it to the Emails field.
func (o *SCIMUser) SetEmails(v []SCIMEmail) {
	o.Emails = v
}

// GetPhoneNumbers returns the PhoneNumbers field value if set, zero value otherwise.
func (o *SCIMUser) GetPhoneNumbers() []SCIMPhoneNumber {
	if o == nil || IsNil(o.PhoneNumbers) {
		var ret []SCIMPhoneNumber
		return ret
	}
	return o.PhoneNumbers
}

// GetPhoneNumbersOk returns a tuple with the PhoneNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetPhoneNumbersOk() ([]SCIMPhoneNumber, bool) {
	if o == nil || IsNil(o.PhoneNumbers) {
		return nil, false
	}
	return o.PhoneNumbers, true
}

// HasPhoneNumbers returns a boolean if a field has been set.
func (o *SCIMUser) HasPhoneNumbers() bool {
	if o != nil && !IsNil(o.PhoneNumbers) {
		return true
	}

	return false
}

// SetPhoneNumbers gets a reference to the given []SCIMPhoneNumber and assigns it to the PhoneNumbers field.
func (o *SCIMUser) SetPhoneNumbers(v []SCIMPhoneNumber) {
	o.PhoneNumbers = v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *SCIMUser) GetAddresses() []SCIMAddress {
	if o == nil || IsNil(o.Addresses) {
		var ret []SCIMAddress
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetAddressesOk() ([]SCIMAddress, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *SCIMUser) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []SCIMAddress and assigns it to the Addresses field.
func (o *SCIMUser) SetAddresses(v []SCIMAddress) {
	o.Addresses = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *SCIMUser) GetGroups() []SCIMGroupMembership {
	if o == nil || IsNil(o.Groups) {
		var ret []SCIMGroupMembership
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMUser) GetGroupsOk() ([]SCIMGroupMembership, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *SCIMUser) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []SCIMGroupMembership and assigns it to the Groups field.
func (o *SCIMUser) SetGroups(v []SCIMGroupMembership) {
	o.Groups = v
}

// GetMeta returns the Meta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SCIMUser) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *SCIMUser) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetUrnIetfParamsScimSchemasExtensionEnterprise20User returns the UrnIetfParamsScimSchemasExtensionEnterprise20User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMUser) GetUrnIetfParamsScimSchemasExtensionEnterprise20User() SCIMEnterpriseUser {
	if o == nil || IsNil(o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Get()) {
		var ret SCIMEnterpriseUser
		return ret
	}
	return *o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Get()
}

// GetUrnIetfParamsScimSchemasExtensionEnterprise20UserOk returns a tuple with the UrnIetfParamsScimSchemasExtensionEnterprise20User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMUser) GetUrnIetfParamsScimSchemasExtensionEnterprise20UserOk() (*SCIMEnterpriseUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Get(), o.UrnIetfParamsScimSchemasExtensionEnterprise20User.IsSet()
}

// HasUrnIetfParamsScimSchemasExtensionEnterprise20User returns a boolean if a field has been set.
func (o *SCIMUser) HasUrnIetfParamsScimSchemasExtensionEnterprise20User() bool {
	if o != nil && o.UrnIetfParamsScimSchemasExtensionEnterprise20User.IsSet() {
		return true
	}

	return false
}

// SetUrnIetfParamsScimSchemasExtensionEnterprise20User gets a reference to the given NullableSCIMEnterpriseUser and assigns it to the UrnIetfParamsScimSchemasExtensionEnterprise20User field.
func (o *SCIMUser) SetUrnIetfParamsScimSchemasExtensionEnterprise20User(v SCIMEnterpriseUser) {
	o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Set(&v)
}
// SetUrnIetfParamsScimSchemasExtensionEnterprise20UserNil sets the value for UrnIetfParamsScimSchemasExtensionEnterprise20User to be an explicit nil
func (o *SCIMUser) SetUrnIetfParamsScimSchemasExtensionEnterprise20UserNil() {
	o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Set(nil)
}

// UnsetUrnIetfParamsScimSchemasExtensionEnterprise20User ensures that no value is present for UrnIetfParamsScimSchemasExtensionEnterprise20User, not even an explicit nil
func (o *SCIMUser) UnsetUrnIetfParamsScimSchemasExtensionEnterprise20User() {
	o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Unset()
}

func (o SCIMUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCIMUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schemas) {
		toSerialize["schemas"] = o.Schemas
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	toSerialize["userName"] = o.UserName
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.NickName.IsSet() {
		toSerialize["nickName"] = o.NickName.Get()
	}
	if o.ProfileUrl.IsSet() {
		toSerialize["profileUrl"] = o.ProfileUrl.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.UserType.IsSet() {
		toSerialize["userType"] = o.UserType.Get()
	}
	if o.PreferredLanguage.IsSet() {
		toSerialize["preferredLanguage"] = o.PreferredLanguage.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Timezone.IsSet() {
		toSerialize["timezone"] = o.Timezone.Get()
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if !IsNil(o.Emails) {
		toSerialize["emails"] = o.Emails
	}
	if !IsNil(o.PhoneNumbers) {
		toSerialize["phoneNumbers"] = o.PhoneNumbers
	}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.UrnIetfParamsScimSchemasExtensionEnterprise20User.IsSet() {
		toSerialize["urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"] = o.UrnIetfParamsScimSchemasExtensionEnterprise20User.Get()
	}
	return toSerialize, nil
}

func (o *SCIMUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSCIMUser := _SCIMUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSCIMUser)

	if err != nil {
		return err
	}

	*o = SCIMUser(varSCIMUser)

	return err
}

type NullableSCIMUser struct {
	value *SCIMUser
	isSet bool
}

func (v NullableSCIMUser) Get() *SCIMUser {
	return v.value
}

func (v *NullableSCIMUser) Set(val *SCIMUser) {
	v.value = val
	v.isSet = true
}

func (v NullableSCIMUser) IsSet() bool {
	return v.isSet
}

func (v *NullableSCIMUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCIMUser(val *SCIMUser) *NullableSCIMUser {
	return &NullableSCIMUser{value: val, isSet: true}
}

func (v NullableSCIMUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCIMUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


