/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsentResponse{}

// ConsentResponse Response for consent operations
type ConsentResponse struct {
	UserId string `json:"user_id"`
	// Current consent status for all types
	Consents map[string]map[string]interface{} `json:"consents"`
}

type _ConsentResponse ConsentResponse

// NewConsentResponse instantiates a new ConsentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsentResponse(userId string, consents map[string]map[string]interface{}) *ConsentResponse {
	this := ConsentResponse{}
	this.UserId = userId
	this.Consents = consents
	return &this
}

// NewConsentResponseWithDefaults instantiates a new ConsentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsentResponseWithDefaults() *ConsentResponse {
	this := ConsentResponse{}
	return &this
}

// GetUserId returns the UserId field value
func (o *ConsentResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ConsentResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ConsentResponse) SetUserId(v string) {
	o.UserId = v
}

// GetConsents returns the Consents field value
func (o *ConsentResponse) GetConsents() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Consents
}

// GetConsentsOk returns a tuple with the Consents field value
// and a boolean to check if the value has been set.
func (o *ConsentResponse) GetConsentsOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.Consents, true
}

// SetConsents sets field value
func (o *ConsentResponse) SetConsents(v map[string]map[string]interface{}) {
	o.Consents = v
}

func (o ConsentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["consents"] = o.Consents
	return toSerialize, nil
}

func (o *ConsentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"consents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsentResponse := _ConsentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsentResponse)

	if err != nil {
		return err
	}

	*o = ConsentResponse(varConsentResponse)

	return err
}

type NullableConsentResponse struct {
	value *ConsentResponse
	isSet bool
}

func (v NullableConsentResponse) Get() *ConsentResponse {
	return v.value
}

func (v *NullableConsentResponse) Set(val *ConsentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentResponse(val *ConsentResponse) *NullableConsentResponse {
	return &NullableConsentResponse{value: val, isSet: true}
}

func (v NullableConsentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
