/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SCIMPhoneNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCIMPhoneNumber{}

// SCIMPhoneNumber SCIM phone number
type SCIMPhoneNumber struct {
	Value string `json:"value"`
	Type NullableString `json:"type,omitempty"`
	Primary *bool `json:"primary,omitempty"`
}

type _SCIMPhoneNumber SCIMPhoneNumber

// NewSCIMPhoneNumber instantiates a new SCIMPhoneNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCIMPhoneNumber(value string) *SCIMPhoneNumber {
	this := SCIMPhoneNumber{}
	this.Value = value
	var primary bool = false
	this.Primary = &primary
	return &this
}

// NewSCIMPhoneNumberWithDefaults instantiates a new SCIMPhoneNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCIMPhoneNumberWithDefaults() *SCIMPhoneNumber {
	this := SCIMPhoneNumber{}
	var primary bool = false
	this.Primary = &primary
	return &this
}

// GetValue returns the Value field value
func (o *SCIMPhoneNumber) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SCIMPhoneNumber) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SCIMPhoneNumber) SetValue(v string) {
	o.Value = v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMPhoneNumber) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMPhoneNumber) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *SCIMPhoneNumber) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *SCIMPhoneNumber) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *SCIMPhoneNumber) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *SCIMPhoneNumber) UnsetType() {
	o.Type.Unset()
}

// GetPrimary returns the Primary field value if set, zero value otherwise.
func (o *SCIMPhoneNumber) GetPrimary() bool {
	if o == nil || IsNil(o.Primary) {
		var ret bool
		return ret
	}
	return *o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMPhoneNumber) GetPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.Primary) {
		return nil, false
	}
	return o.Primary, true
}

// HasPrimary returns a boolean if a field has been set.
func (o *SCIMPhoneNumber) HasPrimary() bool {
	if o != nil && !IsNil(o.Primary) {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given bool and assigns it to the Primary field.
func (o *SCIMPhoneNumber) SetPrimary(v bool) {
	o.Primary = &v
}

func (o SCIMPhoneNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCIMPhoneNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if !IsNil(o.Primary) {
		toSerialize["primary"] = o.Primary
	}
	return toSerialize, nil
}

func (o *SCIMPhoneNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSCIMPhoneNumber := _SCIMPhoneNumber{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSCIMPhoneNumber)

	if err != nil {
		return err
	}

	*o = SCIMPhoneNumber(varSCIMPhoneNumber)

	return err
}

type NullableSCIMPhoneNumber struct {
	value *SCIMPhoneNumber
	isSet bool
}

func (v NullableSCIMPhoneNumber) Get() *SCIMPhoneNumber {
	return v.value
}

func (v *NullableSCIMPhoneNumber) Set(val *SCIMPhoneNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableSCIMPhoneNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableSCIMPhoneNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCIMPhoneNumber(val *SCIMPhoneNumber) *NullableSCIMPhoneNumber {
	return &NullableSCIMPhoneNumber{value: val, isSet: true}
}

func (v NullableSCIMPhoneNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCIMPhoneNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


