/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateAPIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateAPIKeyResponse{}

// RotateAPIKeyResponse Response when rotating API key
type RotateAPIKeyResponse struct {
	KeyId string `json:"key_id"`
	// New API key
	NewApiKey string `json:"new_api_key"`
	Message *string `json:"message,omitempty"`
}

type _RotateAPIKeyResponse RotateAPIKeyResponse

// NewRotateAPIKeyResponse instantiates a new RotateAPIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateAPIKeyResponse(keyId string, newApiKey string) *RotateAPIKeyResponse {
	this := RotateAPIKeyResponse{}
	this.KeyId = keyId
	this.NewApiKey = newApiKey
	var message string = "API key rotated successfully. Update your client configuration."
	this.Message = &message
	return &this
}

// NewRotateAPIKeyResponseWithDefaults instantiates a new RotateAPIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateAPIKeyResponseWithDefaults() *RotateAPIKeyResponse {
	this := RotateAPIKeyResponse{}
	var message string = "API key rotated successfully. Update your client configuration."
	this.Message = &message
	return &this
}

// GetKeyId returns the KeyId field value
func (o *RotateAPIKeyResponse) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *RotateAPIKeyResponse) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *RotateAPIKeyResponse) SetKeyId(v string) {
	o.KeyId = v
}

// GetNewApiKey returns the NewApiKey field value
func (o *RotateAPIKeyResponse) GetNewApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewApiKey
}

// GetNewApiKeyOk returns a tuple with the NewApiKey field value
// and a boolean to check if the value has been set.
func (o *RotateAPIKeyResponse) GetNewApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewApiKey, true
}

// SetNewApiKey sets field value
func (o *RotateAPIKeyResponse) SetNewApiKey(v string) {
	o.NewApiKey = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RotateAPIKeyResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotateAPIKeyResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RotateAPIKeyResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RotateAPIKeyResponse) SetMessage(v string) {
	o.Message = &v
}

func (o RotateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateAPIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_id"] = o.KeyId
	toSerialize["new_api_key"] = o.NewApiKey
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *RotateAPIKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_id",
		"new_api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateAPIKeyResponse := _RotateAPIKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateAPIKeyResponse)

	if err != nil {
		return err
	}

	*o = RotateAPIKeyResponse(varRotateAPIKeyResponse)

	return err
}

type NullableRotateAPIKeyResponse struct {
	value *RotateAPIKeyResponse
	isSet bool
}

func (v NullableRotateAPIKeyResponse) Get() *RotateAPIKeyResponse {
	return v.value
}

func (v *NullableRotateAPIKeyResponse) Set(val *RotateAPIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateAPIKeyResponse(val *RotateAPIKeyResponse) *NullableRotateAPIKeyResponse {
	return &NullableRotateAPIKeyResponse{value: val, isSet: true}
}

func (v NullableRotateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


