/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyUpdateConsentApiV1UsersMeConsentPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyUpdateConsentApiV1UsersMeConsentPost{}

// BodyUpdateConsentApiV1UsersMeConsentPost struct for BodyUpdateConsentApiV1UsersMeConsentPost
type BodyUpdateConsentApiV1UsersMeConsentPost struct {
	Consent ConsentRecord `json:"consent"`
	Credentials NullableHTTPAuthorizationCredentials `json:"credentials,omitempty"`
}

type _BodyUpdateConsentApiV1UsersMeConsentPost BodyUpdateConsentApiV1UsersMeConsentPost

// NewBodyUpdateConsentApiV1UsersMeConsentPost instantiates a new BodyUpdateConsentApiV1UsersMeConsentPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyUpdateConsentApiV1UsersMeConsentPost(consent ConsentRecord) *BodyUpdateConsentApiV1UsersMeConsentPost {
	this := BodyUpdateConsentApiV1UsersMeConsentPost{}
	this.Consent = consent
	return &this
}

// NewBodyUpdateConsentApiV1UsersMeConsentPostWithDefaults instantiates a new BodyUpdateConsentApiV1UsersMeConsentPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyUpdateConsentApiV1UsersMeConsentPostWithDefaults() *BodyUpdateConsentApiV1UsersMeConsentPost {
	this := BodyUpdateConsentApiV1UsersMeConsentPost{}
	return &this
}

// GetConsent returns the Consent field value
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) GetConsent() ConsentRecord {
	if o == nil {
		var ret ConsentRecord
		return ret
	}

	return o.Consent
}

// GetConsentOk returns a tuple with the Consent field value
// and a boolean to check if the value has been set.
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) GetConsentOk() (*ConsentRecord, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Consent, true
}

// SetConsent sets field value
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) SetConsent(v ConsentRecord) {
	o.Consent = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) GetCredentials() HTTPAuthorizationCredentials {
	if o == nil || IsNil(o.Credentials.Get()) {
		var ret HTTPAuthorizationCredentials
		return ret
	}
	return *o.Credentials.Get()
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) GetCredentialsOk() (*HTTPAuthorizationCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credentials.Get(), o.Credentials.IsSet()
}

// HasCredentials returns a boolean if a field has been set.
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) HasCredentials() bool {
	if o != nil && o.Credentials.IsSet() {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given NullableHTTPAuthorizationCredentials and assigns it to the Credentials field.
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) SetCredentials(v HTTPAuthorizationCredentials) {
	o.Credentials.Set(&v)
}
// SetCredentialsNil sets the value for Credentials to be an explicit nil
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) SetCredentialsNil() {
	o.Credentials.Set(nil)
}

// UnsetCredentials ensures that no value is present for Credentials, not even an explicit nil
func (o *BodyUpdateConsentApiV1UsersMeConsentPost) UnsetCredentials() {
	o.Credentials.Unset()
}

func (o BodyUpdateConsentApiV1UsersMeConsentPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyUpdateConsentApiV1UsersMeConsentPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consent"] = o.Consent
	if o.Credentials.IsSet() {
		toSerialize["credentials"] = o.Credentials.Get()
	}
	return toSerialize, nil
}

func (o *BodyUpdateConsentApiV1UsersMeConsentPost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"consent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyUpdateConsentApiV1UsersMeConsentPost := _BodyUpdateConsentApiV1UsersMeConsentPost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyUpdateConsentApiV1UsersMeConsentPost)

	if err != nil {
		return err
	}

	*o = BodyUpdateConsentApiV1UsersMeConsentPost(varBodyUpdateConsentApiV1UsersMeConsentPost)

	return err
}

type NullableBodyUpdateConsentApiV1UsersMeConsentPost struct {
	value *BodyUpdateConsentApiV1UsersMeConsentPost
	isSet bool
}

func (v NullableBodyUpdateConsentApiV1UsersMeConsentPost) Get() *BodyUpdateConsentApiV1UsersMeConsentPost {
	return v.value
}

func (v *NullableBodyUpdateConsentApiV1UsersMeConsentPost) Set(val *BodyUpdateConsentApiV1UsersMeConsentPost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyUpdateConsentApiV1UsersMeConsentPost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyUpdateConsentApiV1UsersMeConsentPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyUpdateConsentApiV1UsersMeConsentPost(val *BodyUpdateConsentApiV1UsersMeConsentPost) *NullableBodyUpdateConsentApiV1UsersMeConsentPost {
	return &NullableBodyUpdateConsentApiV1UsersMeConsentPost{value: val, isSet: true}
}

func (v NullableBodyUpdateConsentApiV1UsersMeConsentPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyUpdateConsentApiV1UsersMeConsentPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
