/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyCreateServicePrincipalApiV1ServicePrincipalsPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyCreateServicePrincipalApiV1ServicePrincipalsPost{}

// BodyCreateServicePrincipalApiV1ServicePrincipalsPost struct for BodyCreateServicePrincipalApiV1ServicePrincipalsPost
type BodyCreateServicePrincipalApiV1ServicePrincipalsPost struct {
	Request CreateServicePrincipalRequest `json:"request"`
	Credentials NullableHTTPAuthorizationCredentials `json:"credentials,omitempty"`
}

type _BodyCreateServicePrincipalApiV1ServicePrincipalsPost BodyCreateServicePrincipalApiV1ServicePrincipalsPost

// NewBodyCreateServicePrincipalApiV1ServicePrincipalsPost instantiates a new BodyCreateServicePrincipalApiV1ServicePrincipalsPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyCreateServicePrincipalApiV1ServicePrincipalsPost(request CreateServicePrincipalRequest) *BodyCreateServicePrincipalApiV1ServicePrincipalsPost {
	this := BodyCreateServicePrincipalApiV1ServicePrincipalsPost{}
	this.Request = request
	return &this
}

// NewBodyCreateServicePrincipalApiV1ServicePrincipalsPostWithDefaults instantiates a new BodyCreateServicePrincipalApiV1ServicePrincipalsPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyCreateServicePrincipalApiV1ServicePrincipalsPostWithDefaults() *BodyCreateServicePrincipalApiV1ServicePrincipalsPost {
	this := BodyCreateServicePrincipalApiV1ServicePrincipalsPost{}
	return &this
}

// GetRequest returns the Request field value
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) GetRequest() CreateServicePrincipalRequest {
	if o == nil {
		var ret CreateServicePrincipalRequest
		return ret
	}

	return o.Request
}

// GetRequestOk returns a tuple with the Request field value
// and a boolean to check if the value has been set.
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) GetRequestOk() (*CreateServicePrincipalRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Request, true
}

// SetRequest sets field value
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) SetRequest(v CreateServicePrincipalRequest) {
	o.Request = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) GetCredentials() HTTPAuthorizationCredentials {
	if o == nil || IsNil(o.Credentials.Get()) {
		var ret HTTPAuthorizationCredentials
		return ret
	}
	return *o.Credentials.Get()
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) GetCredentialsOk() (*HTTPAuthorizationCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credentials.Get(), o.Credentials.IsSet()
}

// HasCredentials returns a boolean if a field has been set.
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) HasCredentials() bool {
	if o != nil && o.Credentials.IsSet() {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given NullableHTTPAuthorizationCredentials and assigns it to the Credentials field.
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) SetCredentials(v HTTPAuthorizationCredentials) {
	o.Credentials.Set(&v)
}
// SetCredentialsNil sets the value for Credentials to be an explicit nil
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) SetCredentialsNil() {
	o.Credentials.Set(nil)
}

// UnsetCredentials ensures that no value is present for Credentials, not even an explicit nil
func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) UnsetCredentials() {
	o.Credentials.Unset()
}

func (o BodyCreateServicePrincipalApiV1ServicePrincipalsPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyCreateServicePrincipalApiV1ServicePrincipalsPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["request"] = o.Request
	if o.Credentials.IsSet() {
		toSerialize["credentials"] = o.Credentials.Get()
	}
	return toSerialize, nil
}

func (o *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"request",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyCreateServicePrincipalApiV1ServicePrincipalsPost := _BodyCreateServicePrincipalApiV1ServicePrincipalsPost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyCreateServicePrincipalApiV1ServicePrincipalsPost)

	if err != nil {
		return err
	}

	*o = BodyCreateServicePrincipalApiV1ServicePrincipalsPost(varBodyCreateServicePrincipalApiV1ServicePrincipalsPost)

	return err
}

type NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost struct {
	value *BodyCreateServicePrincipalApiV1ServicePrincipalsPost
	isSet bool
}

func (v NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost) Get() *BodyCreateServicePrincipalApiV1ServicePrincipalsPost {
	return v.value
}

func (v *NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost) Set(val *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost(val *BodyCreateServicePrincipalApiV1ServicePrincipalsPost) *NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost {
	return &NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost{value: val, isSet: true}
}

func (v NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyCreateServicePrincipalApiV1ServicePrincipalsPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


