/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateSecretResponse{}

// RotateSecretResponse Response when rotating service principal secret
type RotateSecretResponse struct {
	ServiceId string `json:"service_id"`
	// New client secret
	ClientSecret string `json:"client_secret"`
	Message *string `json:"message,omitempty"`
}

type _RotateSecretResponse RotateSecretResponse

// NewRotateSecretResponse instantiates a new RotateSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateSecretResponse(serviceId string, clientSecret string) *RotateSecretResponse {
	this := RotateSecretResponse{}
	this.ServiceId = serviceId
	this.ClientSecret = clientSecret
	var message string = "Secret rotated successfully. Update your service configuration."
	this.Message = &message
	return &this
}

// NewRotateSecretResponseWithDefaults instantiates a new RotateSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateSecretResponseWithDefaults() *RotateSecretResponse {
	this := RotateSecretResponse{}
	var message string = "Secret rotated successfully. Update your service configuration."
	this.Message = &message
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *RotateSecretResponse) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *RotateSecretResponse) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *RotateSecretResponse) SetServiceId(v string) {
	o.ServiceId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *RotateSecretResponse) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *RotateSecretResponse) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *RotateSecretResponse) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RotateSecretResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotateSecretResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RotateSecretResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RotateSecretResponse) SetMessage(v string) {
	o.Message = &v
}

func (o RotateSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["client_secret"] = o.ClientSecret
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *RotateSecretResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateSecretResponse := _RotateSecretResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateSecretResponse)

	if err != nil {
		return err
	}

	*o = RotateSecretResponse(varRotateSecretResponse)

	return err
}

type NullableRotateSecretResponse struct {
	value *RotateSecretResponse
	isSet bool
}

func (v NullableRotateSecretResponse) Get() *RotateSecretResponse {
	return v.value
}

func (v *NullableRotateSecretResponse) Set(val *RotateSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateSecretResponse(val *RotateSecretResponse) *NullableRotateSecretResponse {
	return &NullableRotateSecretResponse{value: val, isSet: true}
}

func (v NullableRotateSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


