/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServicePrincipalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicePrincipalResponse{}

// ServicePrincipalResponse Response containing service principal details
type ServicePrincipalResponse struct {
	ServiceId string `json:"service_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	AuthenticationMode string `json:"authentication_mode"`
	AssociatedUserId NullableString `json:"associated_user_id"`
	OwnerUserId NullableString `json:"owner_user_id"`
	InheritPermissions bool `json:"inherit_permissions"`
	Enabled bool `json:"enabled"`
	CreatedAt NullableString `json:"created_at"`
}

type _ServicePrincipalResponse ServicePrincipalResponse

// NewServicePrincipalResponse instantiates a new ServicePrincipalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicePrincipalResponse(serviceId string, name string, description string, authenticationMode string, associatedUserId NullableString, ownerUserId NullableString, inheritPermissions bool, enabled bool, createdAt NullableString) *ServicePrincipalResponse {
	this := ServicePrincipalResponse{}
	this.ServiceId = serviceId
	this.Name = name
	this.Description = description
	this.AuthenticationMode = authenticationMode
	this.AssociatedUserId = associatedUserId
	this.OwnerUserId = ownerUserId
	this.InheritPermissions = inheritPermissions
	this.Enabled = enabled
	this.CreatedAt = createdAt
	return &this
}

// NewServicePrincipalResponseWithDefaults instantiates a new ServicePrincipalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicePrincipalResponseWithDefaults() *ServicePrincipalResponse {
	this := ServicePrincipalResponse{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ServicePrincipalResponse) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServicePrincipalResponse) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServicePrincipalResponse) SetServiceId(v string) {
	o.ServiceId = v
}

// GetName returns the Name field value
func (o *ServicePrincipalResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServicePrincipalResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServicePrincipalResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ServicePrincipalResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ServicePrincipalResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ServicePrincipalResponse) SetDescription(v string) {
	o.Description = v
}

// GetAuthenticationMode returns the AuthenticationMode field value
func (o *ServicePrincipalResponse) GetAuthenticationMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationMode
}

// GetAuthenticationModeOk returns a tuple with the AuthenticationMode field value
// and a boolean to check if the value has been set.
func (o *ServicePrincipalResponse) GetAuthenticationModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationMode, true
}

// SetAuthenticationMode sets field value
func (o *ServicePrincipalResponse) SetAuthenticationMode(v string) {
	o.AuthenticationMode = v
}

// GetAssociatedUserId returns the AssociatedUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ServicePrincipalResponse) GetAssociatedUserId() string {
	if o == nil || o.AssociatedUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.AssociatedUserId.Get()
}

// GetAssociatedUserIdOk returns a tuple with the AssociatedUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServicePrincipalResponse) GetAssociatedUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssociatedUserId.Get(), o.AssociatedUserId.IsSet()
}

// SetAssociatedUserId sets field value
func (o *ServicePrincipalResponse) SetAssociatedUserId(v string) {
	o.AssociatedUserId.Set(&v)
}

// GetOwnerUserId returns the OwnerUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ServicePrincipalResponse) GetOwnerUserId() string {
	if o == nil || o.OwnerUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OwnerUserId.Get()
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServicePrincipalResponse) GetOwnerUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerUserId.Get(), o.OwnerUserId.IsSet()
}

// SetOwnerUserId sets field value
func (o *ServicePrincipalResponse) SetOwnerUserId(v string) {
	o.OwnerUserId.Set(&v)
}

// GetInheritPermissions returns the InheritPermissions field value
func (o *ServicePrincipalResponse) GetInheritPermissions() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InheritPermissions
}

// GetInheritPermissionsOk returns a tuple with the InheritPermissions field value
// and a boolean to check if the value has been set.
func (o *ServicePrincipalResponse) GetInheritPermissionsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InheritPermissions, true
}

// SetInheritPermissions sets field value
func (o *ServicePrincipalResponse) SetInheritPermissions(v bool) {
	o.InheritPermissions = v
}

// GetEnabled returns the Enabled field value
func (o *ServicePrincipalResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ServicePrincipalResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ServicePrincipalResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ServicePrincipalResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServicePrincipalResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *ServicePrincipalResponse) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

func (o ServicePrincipalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicePrincipalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["authentication_mode"] = o.AuthenticationMode
	toSerialize["associated_user_id"] = o.AssociatedUserId.Get()
	toSerialize["owner_user_id"] = o.OwnerUserId.Get()
	toSerialize["inherit_permissions"] = o.InheritPermissions
	toSerialize["enabled"] = o.Enabled
	toSerialize["created_at"] = o.CreatedAt.Get()
	return toSerialize, nil
}

func (o *ServicePrincipalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"name",
		"description",
		"authentication_mode",
		"associated_user_id",
		"owner_user_id",
		"inherit_permissions",
		"enabled",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicePrincipalResponse := _ServicePrincipalResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServicePrincipalResponse)

	if err != nil {
		return err
	}

	*o = ServicePrincipalResponse(varServicePrincipalResponse)

	return err
}

type NullableServicePrincipalResponse struct {
	value *ServicePrincipalResponse
	isSet bool
}

func (v NullableServicePrincipalResponse) Get() *ServicePrincipalResponse {
	return v.value
}

func (v *NullableServicePrincipalResponse) Set(val *ServicePrincipalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServicePrincipalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServicePrincipalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicePrincipalResponse(val *ServicePrincipalResponse) *NullableServicePrincipalResponse {
	return &NullableServicePrincipalResponse{value: val, isSet: true}
}

func (v NullableServicePrincipalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicePrincipalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
