/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateServicePrincipalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateServicePrincipalRequest{}

// CreateServicePrincipalRequest Request to create a new service principal
type CreateServicePrincipalRequest struct {
	// Human-readable name for the service
	Name string `json:"name"`
	// Purpose/description of the service
	Description string `json:"description"`
	// Authentication mode: 'client_credentials' or 'service_account_user'
	AuthenticationMode *string `json:"authentication_mode,omitempty"`
	AssociatedUserId NullableString `json:"associated_user_id,omitempty"`
	// Whether to inherit permissions from associated user
	InheritPermissions *bool `json:"inherit_permissions,omitempty"`
}

type _CreateServicePrincipalRequest CreateServicePrincipalRequest

// NewCreateServicePrincipalRequest instantiates a new CreateServicePrincipalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateServicePrincipalRequest(name string, description string) *CreateServicePrincipalRequest {
	this := CreateServicePrincipalRequest{}
	this.Name = name
	this.Description = description
	var authenticationMode string = "client_credentials"
	this.AuthenticationMode = &authenticationMode
	var inheritPermissions bool = false
	this.InheritPermissions = &inheritPermissions
	return &this
}

// NewCreateServicePrincipalRequestWithDefaults instantiates a new CreateServicePrincipalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateServicePrincipalRequestWithDefaults() *CreateServicePrincipalRequest {
	this := CreateServicePrincipalRequest{}
	var authenticationMode string = "client_credentials"
	this.AuthenticationMode = &authenticationMode
	var inheritPermissions bool = false
	this.InheritPermissions = &inheritPermissions
	return &this
}

// GetName returns the Name field value
func (o *CreateServicePrincipalRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateServicePrincipalRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreateServicePrincipalRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateServicePrincipalRequest) SetDescription(v string) {
	o.Description = v
}

// GetAuthenticationMode returns the AuthenticationMode field value if set, zero value otherwise.
func (o *CreateServicePrincipalRequest) GetAuthenticationMode() string {
	if o == nil || IsNil(o.AuthenticationMode) {
		var ret string
		return ret
	}
	return *o.AuthenticationMode
}

// GetAuthenticationModeOk returns a tuple with the AuthenticationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalRequest) GetAuthenticationModeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthenticationMode) {
		return nil, false
	}
	return o.AuthenticationMode, true
}

// HasAuthenticationMode returns a boolean if a field has been set.
func (o *CreateServicePrincipalRequest) HasAuthenticationMode() bool {
	if o != nil && !IsNil(o.AuthenticationMode) {
		return true
	}

	return false
}

// SetAuthenticationMode gets a reference to the given string and assigns it to the AuthenticationMode field.
func (o *CreateServicePrincipalRequest) SetAuthenticationMode(v string) {
	o.AuthenticationMode = &v
}

// GetAssociatedUserId returns the AssociatedUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateServicePrincipalRequest) GetAssociatedUserId() string {
	if o == nil || IsNil(o.AssociatedUserId.Get()) {
		var ret string
		return ret
	}
	return *o.AssociatedUserId.Get()
}

// GetAssociatedUserIdOk returns a tuple with the AssociatedUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateServicePrincipalRequest) GetAssociatedUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssociatedUserId.Get(), o.AssociatedUserId.IsSet()
}

// HasAssociatedUserId returns a boolean if a field has been set.
func (o *CreateServicePrincipalRequest) HasAssociatedUserId() bool {
	if o != nil && o.AssociatedUserId.IsSet() {
		return true
	}

	return false
}

// SetAssociatedUserId gets a reference to the given NullableString and assigns it to the AssociatedUserId field.
func (o *CreateServicePrincipalRequest) SetAssociatedUserId(v string) {
	o.AssociatedUserId.Set(&v)
}
// SetAssociatedUserIdNil sets the value for AssociatedUserId to be an explicit nil
func (o *CreateServicePrincipalRequest) SetAssociatedUserIdNil() {
	o.AssociatedUserId.Set(nil)
}

// UnsetAssociatedUserId ensures that no value is present for AssociatedUserId, not even an explicit nil
func (o *CreateServicePrincipalRequest) UnsetAssociatedUserId() {
	o.AssociatedUserId.Unset()
}

// GetInheritPermissions returns the InheritPermissions field value if set, zero value otherwise.
func (o *CreateServicePrincipalRequest) GetInheritPermissions() bool {
	if o == nil || IsNil(o.InheritPermissions) {
		var ret bool
		return ret
	}
	return *o.InheritPermissions
}

// GetInheritPermissionsOk returns a tuple with the InheritPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServicePrincipalRequest) GetInheritPermissionsOk() (*bool, bool) {
	if o == nil || IsNil(o.InheritPermissions) {
		return nil, false
	}
	return o.InheritPermissions, true
}

// HasInheritPermissions returns a boolean if a field has been set.
func (o *CreateServicePrincipalRequest) HasInheritPermissions() bool {
	if o != nil && !IsNil(o.InheritPermissions) {
		return true
	}

	return false
}

// SetInheritPermissions gets a reference to the given bool and assigns it to the InheritPermissions field.
func (o *CreateServicePrincipalRequest) SetInheritPermissions(v bool) {
	o.InheritPermissions = &v
}

func (o CreateServicePrincipalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateServicePrincipalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.AuthenticationMode) {
		toSerialize["authentication_mode"] = o.AuthenticationMode
	}
	if o.AssociatedUserId.IsSet() {
		toSerialize["associated_user_id"] = o.AssociatedUserId.Get()
	}
	if !IsNil(o.InheritPermissions) {
		toSerialize["inherit_permissions"] = o.InheritPermissions
	}
	return toSerialize, nil
}

func (o *CreateServicePrincipalRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateServicePrincipalRequest := _CreateServicePrincipalRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateServicePrincipalRequest)

	if err != nil {
		return err
	}

	*o = CreateServicePrincipalRequest(varCreateServicePrincipalRequest)

	return err
}

type NullableCreateServicePrincipalRequest struct {
	value *CreateServicePrincipalRequest
	isSet bool
}

func (v NullableCreateServicePrincipalRequest) Get() *CreateServicePrincipalRequest {
	return v.value
}

func (v *NullableCreateServicePrincipalRequest) Set(val *CreateServicePrincipalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateServicePrincipalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateServicePrincipalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateServicePrincipalRequest(val *CreateServicePrincipalRequest) *NullableCreateServicePrincipalRequest {
	return &NullableCreateServicePrincipalRequest{value: val, isSet: true}
}

func (v NullableCreateServicePrincipalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateServicePrincipalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


