/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the APIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIKeyResponse{}

// APIKeyResponse Response containing API key metadata
type APIKeyResponse struct {
	KeyId string `json:"key_id"`
	Name string `json:"name"`
	Created string `json:"created"`
	ExpiresAt string `json:"expires_at"`
	LastUsed NullableString `json:"last_used,omitempty"`
}

type _APIKeyResponse APIKeyResponse

// NewAPIKeyResponse instantiates a new APIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIKeyResponse(keyId string, name string, created string, expiresAt string) *APIKeyResponse {
	this := APIKeyResponse{}
	this.KeyId = keyId
	this.Name = name
	this.Created = created
	this.ExpiresAt = expiresAt
	return &this
}

// NewAPIKeyResponseWithDefaults instantiates a new APIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIKeyResponseWithDefaults() *APIKeyResponse {
	this := APIKeyResponse{}
	return &this
}

// GetKeyId returns the KeyId field value
func (o *APIKeyResponse) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *APIKeyResponse) SetKeyId(v string) {
	o.KeyId = v
}

// GetName returns the Name field value
func (o *APIKeyResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *APIKeyResponse) SetName(v string) {
	o.Name = v
}

// GetCreated returns the Created field value
func (o *APIKeyResponse) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *APIKeyResponse) SetCreated(v string) {
	o.Created = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *APIKeyResponse) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *APIKeyResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *APIKeyResponse) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *APIKeyResponse) GetLastUsed() string {
	if o == nil || IsNil(o.LastUsed.Get()) {
		var ret string
		return ret
	}
	return *o.LastUsed.Get()
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *APIKeyResponse) GetLastUsedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsed.Get(), o.LastUsed.IsSet()
}

// HasLastUsed returns a boolean if a field has been set.
func (o *APIKeyResponse) HasLastUsed() bool {
	if o != nil && o.LastUsed.IsSet() {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given NullableString and assigns it to the LastUsed field.
func (o *APIKeyResponse) SetLastUsed(v string) {
	o.LastUsed.Set(&v)
}
// SetLastUsedNil sets the value for LastUsed to be an explicit nil
func (o *APIKeyResponse) SetLastUsedNil() {
	o.LastUsed.Set(nil)
}

// UnsetLastUsed ensures that no value is present for LastUsed, not even an explicit nil
func (o *APIKeyResponse) UnsetLastUsed() {
	o.LastUsed.Unset()
}

func (o APIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_id"] = o.KeyId
	toSerialize["name"] = o.Name
	toSerialize["created"] = o.Created
	toSerialize["expires_at"] = o.ExpiresAt
	if o.LastUsed.IsSet() {
		toSerialize["last_used"] = o.LastUsed.Get()
	}
	return toSerialize, nil
}

func (o *APIKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_id",
		"name",
		"created",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIKeyResponse := _APIKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIKeyResponse)

	if err != nil {
		return err
	}

	*o = APIKeyResponse(varAPIKeyResponse)

	return err
}

type NullableAPIKeyResponse struct {
	value *APIKeyResponse
	isSet bool
}

func (v NullableAPIKeyResponse) Get() *APIKeyResponse {
	return v.value
}

func (v *NullableAPIKeyResponse) Set(val *APIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIKeyResponse(val *APIKeyResponse) *NullableAPIKeyResponse {
	return &NullableAPIKeyResponse{value: val, isSet: true}
}

func (v NullableAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


