/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserDataExport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDataExport{}

// UserDataExport Complete user data export for GDPR compliance  Includes all personal data associated with a user.
type UserDataExport struct {
	// Unique export identifier
	ExportId string `json:"export_id"`
	// ISO timestamp of export
	ExportTimestamp string `json:"export_timestamp"`
	// User identifier
	UserId string `json:"user_id"`
	// Username
	Username string `json:"username"`
	// User email address
	Email string `json:"email"`
	// User profile data
	Profile map[string]interface{} `json:"profile,omitempty"`
	// Active and recent sessions
	Sessions []*map[string]interface{} `json:"sessions,omitempty"`
	// Conversation history
	Conversations []*map[string]interface{} `json:"conversations,omitempty"`
	// User preferences and settings
	Preferences map[string]interface{} `json:"preferences,omitempty"`
	// User activity audit log
	AuditLog []*map[string]interface{} `json:"audit_log,omitempty"`
	// Consent records
	Consents []*map[string]interface{} `json:"consents,omitempty"`
	// Additional metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _UserDataExport UserDataExport

// NewUserDataExport instantiates a new UserDataExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDataExport(exportId string, exportTimestamp string, userId string, username string, email string) *UserDataExport {
	this := UserDataExport{}
	this.ExportId = exportId
	this.ExportTimestamp = exportTimestamp
	this.UserId = userId
	this.Username = username
	this.Email = email
	return &this
}

// NewUserDataExportWithDefaults instantiates a new UserDataExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDataExportWithDefaults() *UserDataExport {
	this := UserDataExport{}
	return &this
}

// GetExportId returns the ExportId field value
func (o *UserDataExport) GetExportId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExportId
}

// GetExportIdOk returns a tuple with the ExportId field value
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetExportIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExportId, true
}

// SetExportId sets field value
func (o *UserDataExport) SetExportId(v string) {
	o.ExportId = v
}

// GetExportTimestamp returns the ExportTimestamp field value
func (o *UserDataExport) GetExportTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExportTimestamp
}

// GetExportTimestampOk returns a tuple with the ExportTimestamp field value
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetExportTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExportTimestamp, true
}

// SetExportTimestamp sets field value
func (o *UserDataExport) SetExportTimestamp(v string) {
	o.ExportTimestamp = v
}

// GetUserId returns the UserId field value
func (o *UserDataExport) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserDataExport) SetUserId(v string) {
	o.UserId = v
}

// GetUsername returns the Username field value
func (o *UserDataExport) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserDataExport) SetUsername(v string) {
	o.Username = v
}

// GetEmail returns the Email field value
func (o *UserDataExport) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserDataExport) SetEmail(v string) {
	o.Email = v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *UserDataExport) GetProfile() map[string]interface{} {
	if o == nil || IsNil(o.Profile) {
		var ret map[string]interface{}
		return ret
	}
	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Profile) {
		return map[string]interface{}{}, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *UserDataExport) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given map[string]interface{} and assigns it to the Profile field.
func (o *UserDataExport) SetProfile(v map[string]interface{}) {
	o.Profile = v
}

// GetSessions returns the Sessions field value if set, zero value otherwise.
func (o *UserDataExport) GetSessions() []*map[string]interface{} {
	if o == nil || IsNil(o.Sessions) {
		var ret []*map[string]interface{}
		return ret
	}
	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetSessionsOk() ([]*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Sessions) {
		return nil, false
	}
	return o.Sessions, true
}

// HasSessions returns a boolean if a field has been set.
func (o *UserDataExport) HasSessions() bool {
	if o != nil && !IsNil(o.Sessions) {
		return true
	}

	return false
}

// SetSessions gets a reference to the given []*map[string]interface{} and assigns it to the Sessions field.
func (o *UserDataExport) SetSessions(v []*map[string]interface{}) {
	o.Sessions = v
}

// GetConversations returns the Conversations field value if set, zero value otherwise.
func (o *UserDataExport) GetConversations() []*map[string]interface{} {
	if o == nil || IsNil(o.Conversations) {
		var ret []*map[string]interface{}
		return ret
	}
	return o.Conversations
}

// GetConversationsOk returns a tuple with the Conversations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetConversationsOk() ([]*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conversations) {
		return nil, false
	}
	return o.Conversations, true
}

// HasConversations returns a boolean if a field has been set.
func (o *UserDataExport) HasConversations() bool {
	if o != nil && !IsNil(o.Conversations) {
		return true
	}

	return false
}

// SetConversations gets a reference to the given []*map[string]interface{} and assigns it to the Conversations field.
func (o *UserDataExport) SetConversations(v []*map[string]interface{}) {
	o.Conversations = v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *UserDataExport) GetPreferences() map[string]interface{} {
	if o == nil || IsNil(o.Preferences) {
		var ret map[string]interface{}
		return ret
	}
	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Preferences) {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *UserDataExport) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given map[string]interface{} and assigns it to the Preferences field.
func (o *UserDataExport) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

// GetAuditLog returns the AuditLog field value if set, zero value otherwise.
func (o *UserDataExport) GetAuditLog() []*map[string]interface{} {
	if o == nil || IsNil(o.AuditLog) {
		var ret []*map[string]interface{}
		return ret
	}
	return o.AuditLog
}

// GetAuditLogOk returns a tuple with the AuditLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetAuditLogOk() ([]*map[string]interface{}, bool) {
	if o == nil || IsNil(o.AuditLog) {
		return nil, false
	}
	return o.AuditLog, true
}

// HasAuditLog returns a boolean if a field has been set.
func (o *UserDataExport) HasAuditLog() bool {
	if o != nil && !IsNil(o.AuditLog) {
		return true
	}

	return false
}

// SetAuditLog gets a reference to the given []*map[string]interface{} and assigns it to the AuditLog field.
func (o *UserDataExport) SetAuditLog(v []*map[string]interface{}) {
	o.AuditLog = v
}

// GetConsents returns the Consents field value if set, zero value otherwise.
func (o *UserDataExport) GetConsents() []*map[string]interface{} {
	if o == nil || IsNil(o.Consents) {
		var ret []*map[string]interface{}
		return ret
	}
	return o.Consents
}

// GetConsentsOk returns a tuple with the Consents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetConsentsOk() ([]*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Consents) {
		return nil, false
	}
	return o.Consents, true
}

// HasConsents returns a boolean if a field has been set.
func (o *UserDataExport) HasConsents() bool {
	if o != nil && !IsNil(o.Consents) {
		return true
	}

	return false
}

// SetConsents gets a reference to the given []*map[string]interface{} and assigns it to the Consents field.
func (o *UserDataExport) SetConsents(v []*map[string]interface{}) {
	o.Consents = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UserDataExport) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataExport) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UserDataExport) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UserDataExport) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o UserDataExport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDataExport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["export_id"] = o.ExportId
	toSerialize["export_timestamp"] = o.ExportTimestamp
	toSerialize["user_id"] = o.UserId
	toSerialize["username"] = o.Username
	toSerialize["email"] = o.Email
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Sessions) {
		toSerialize["sessions"] = o.Sessions
	}
	if !IsNil(o.Conversations) {
		toSerialize["conversations"] = o.Conversations
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	if !IsNil(o.AuditLog) {
		toSerialize["audit_log"] = o.AuditLog
	}
	if !IsNil(o.Consents) {
		toSerialize["consents"] = o.Consents
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *UserDataExport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"export_id",
		"export_timestamp",
		"user_id",
		"username",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserDataExport := _UserDataExport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserDataExport)

	if err != nil {
		return err
	}

	*o = UserDataExport(varUserDataExport)

	return err
}

type NullableUserDataExport struct {
	value *UserDataExport
	isSet bool
}

func (v NullableUserDataExport) Get() *UserDataExport {
	return v.value
}

func (v *NullableUserDataExport) Set(val *UserDataExport) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDataExport) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDataExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDataExport(val *UserDataExport) *NullableUserDataExport {
	return &NullableUserDataExport{value: val, isSet: true}
}

func (v NullableUserDataExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDataExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


