/*
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mcpclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyCreateUserScimV2UsersPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyCreateUserScimV2UsersPost{}

// BodyCreateUserScimV2UsersPost struct for BodyCreateUserScimV2UsersPost
type BodyCreateUserScimV2UsersPost struct {
	UserData map[string]interface{} `json:"user_data"`
	Credentials NullableHTTPAuthorizationCredentials `json:"credentials,omitempty"`
}

type _BodyCreateUserScimV2UsersPost BodyCreateUserScimV2UsersPost

// NewBodyCreateUserScimV2UsersPost instantiates a new BodyCreateUserScimV2UsersPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyCreateUserScimV2UsersPost(userData map[string]interface{}) *BodyCreateUserScimV2UsersPost {
	this := BodyCreateUserScimV2UsersPost{}
	this.UserData = userData
	return &this
}

// NewBodyCreateUserScimV2UsersPostWithDefaults instantiates a new BodyCreateUserScimV2UsersPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyCreateUserScimV2UsersPostWithDefaults() *BodyCreateUserScimV2UsersPost {
	this := BodyCreateUserScimV2UsersPost{}
	return &this
}

// GetUserData returns the UserData field value
func (o *BodyCreateUserScimV2UsersPost) GetUserData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.UserData
}

// GetUserDataOk returns a tuple with the UserData field value
// and a boolean to check if the value has been set.
func (o *BodyCreateUserScimV2UsersPost) GetUserDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.UserData, true
}

// SetUserData sets field value
func (o *BodyCreateUserScimV2UsersPost) SetUserData(v map[string]interface{}) {
	o.UserData = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BodyCreateUserScimV2UsersPost) GetCredentials() HTTPAuthorizationCredentials {
	if o == nil || IsNil(o.Credentials.Get()) {
		var ret HTTPAuthorizationCredentials
		return ret
	}
	return *o.Credentials.Get()
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BodyCreateUserScimV2UsersPost) GetCredentialsOk() (*HTTPAuthorizationCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credentials.Get(), o.Credentials.IsSet()
}

// HasCredentials returns a boolean if a field has been set.
func (o *BodyCreateUserScimV2UsersPost) HasCredentials() bool {
	if o != nil && o.Credentials.IsSet() {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given NullableHTTPAuthorizationCredentials and assigns it to the Credentials field.
func (o *BodyCreateUserScimV2UsersPost) SetCredentials(v HTTPAuthorizationCredentials) {
	o.Credentials.Set(&v)
}
// SetCredentialsNil sets the value for Credentials to be an explicit nil
func (o *BodyCreateUserScimV2UsersPost) SetCredentialsNil() {
	o.Credentials.Set(nil)
}

// UnsetCredentials ensures that no value is present for Credentials, not even an explicit nil
func (o *BodyCreateUserScimV2UsersPost) UnsetCredentials() {
	o.Credentials.Unset()
}

func (o BodyCreateUserScimV2UsersPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyCreateUserScimV2UsersPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_data"] = o.UserData
	if o.Credentials.IsSet() {
		toSerialize["credentials"] = o.Credentials.Get()
	}
	return toSerialize, nil
}

func (o *BodyCreateUserScimV2UsersPost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyCreateUserScimV2UsersPost := _BodyCreateUserScimV2UsersPost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyCreateUserScimV2UsersPost)

	if err != nil {
		return err
	}

	*o = BodyCreateUserScimV2UsersPost(varBodyCreateUserScimV2UsersPost)

	return err
}

type NullableBodyCreateUserScimV2UsersPost struct {
	value *BodyCreateUserScimV2UsersPost
	isSet bool
}

func (v NullableBodyCreateUserScimV2UsersPost) Get() *BodyCreateUserScimV2UsersPost {
	return v.value
}

func (v *NullableBodyCreateUserScimV2UsersPost) Set(val *BodyCreateUserScimV2UsersPost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyCreateUserScimV2UsersPost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyCreateUserScimV2UsersPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyCreateUserScimV2UsersPost(val *BodyCreateUserScimV2UsersPost) *NullableBodyCreateUserScimV2UsersPost {
	return &NullableBodyCreateUserScimV2UsersPost{value: val, isSet: true}
}

func (v NullableBodyCreateUserScimV2UsersPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyCreateUserScimV2UsersPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
