"""
SOC2 Compliance Prometheus metrics.

Metrics for SOC2 compliance dashboard:
- compliance_score: Current compliance score (0-100%)
- evidence_items_total: Total evidence items by status and control category
- audit_logs_total: Total audit log events by event type
- access_review_items_total: Total access review items by status
- compliance_job_executions_total: Job execution count by job_type and status
- compliance_report_generated_total: Reports generated by report_type

These metrics are scraped by Alloy and displayed in the SOC2 Compliance Grafana dashboard.
"""

from typing import Any

# Lazy-load prometheus_client to handle missing dependency
_metrics_available: bool | None = None
_compliance_score_gauge: Any = None
_evidence_items_total: Any = None
_audit_logs_total: Any = None
_access_review_items_total: Any = None
_compliance_job_executions_total: Any = None
_compliance_report_generated_total: Any = None
_gdpr_anonymization_total: Any = None
_gdpr_data_export_total: Any = None
_gdpr_data_deletion_total: Any = None
_gdpr_retention_cleanup_total: Any = None


def _init_metrics() -> bool:
    """Initialize SOC2 compliance metrics lazily."""
    global _metrics_available  # noqa: PLW0603
    global _compliance_score_gauge  # noqa: PLW0603
    global _evidence_items_total  # noqa: PLW0603
    global _audit_logs_total  # noqa: PLW0603
    global _access_review_items_total  # noqa: PLW0603
    global _compliance_job_executions_total  # noqa: PLW0603
    global _compliance_report_generated_total  # noqa: PLW0603
    global _gdpr_anonymization_total  # noqa: PLW0603
    global _gdpr_data_export_total  # noqa: PLW0603
    global _gdpr_data_deletion_total  # noqa: PLW0603
    global _gdpr_retention_cleanup_total  # noqa: PLW0603

    if _metrics_available is not None:
        return _metrics_available

    try:
        from prometheus_client import Counter, Gauge

        _compliance_score_gauge = Gauge(
            "compliance_score",
            "Current SOC2 compliance score (0-100%)",
            [],
        )

        _evidence_items_total = Counter(
            "evidence_items_total",
            "Total evidence items collected",
            ["status", "control_category"],  # status: success, failure, partial
        )

        _audit_logs_total = Counter(
            "audit_logs_total",
            "Total audit log events",
            ["event_type"],  # event_type: login, logout, access_denied, etc.
        )

        _access_review_items_total = Counter(
            "access_review_items_total",
            "Total access review items",
            ["status"],  # status: approved, revoked, pending
        )

        _compliance_job_executions_total = Counter(
            "compliance_job_executions_total",
            "Total compliance job executions",
            ["job_type", "status"],  # job_type: daily_check, weekly_access_review, etc.
        )

        _compliance_report_generated_total = Counter(
            "compliance_report_generated_total",
            "Total compliance reports generated",
            ["report_type"],  # report_type: daily, weekly, monthly
        )

        _gdpr_anonymization_total = Counter(
            "gdpr_anonymization_total",
            "Total GDPR anonymization operations",
            ["operation"],  # operation: audit_logs, user_data, etc.
        )

        _gdpr_data_export_total = Counter(
            "gdpr_data_export_total",
            "Total GDPR data export operations (DSAR Article 15/20)",
            ["format", "status"],  # format: json, csv; status: success, failure
        )

        _gdpr_data_deletion_total = Counter(
            "gdpr_data_deletion_total",
            "Total GDPR data deletion operations (Article 17)",
            ["operation", "status"],  # operation: full, sessions, conversations, etc.
        )

        _gdpr_retention_cleanup_total = Counter(
            "gdpr_retention_cleanup_total",
            "Total GDPR retention cleanup operations (Article 5)",
            ["data_type", "status"],  # data_type: sessions, conversations, audit_logs
        )

        _metrics_available = True
        return True

    except ImportError:
        _metrics_available = False
        return False


# Initialize on module load
_init_metrics()


def record_compliance_score(score: float) -> None:
    """
    Record the current compliance score.

    Args:
        score: Compliance score (0-100%)
    """
    if not _metrics_available:
        return

    try:
        if _compliance_score_gauge:
            _compliance_score_gauge.set(score)
    except Exception:
        pass  # Don't let metrics failures break the app


def record_evidence_item(status: str, control_category: str) -> None:
    """
    Record an evidence item collection.

    Args:
        status: Evidence status ("success", "failure", "partial")
        control_category: Control category (e.g., "CC6.1", "CC7.2", "A1.2")
    """
    if not _metrics_available:
        return

    try:
        if _evidence_items_total:
            _evidence_items_total.labels(status=status, control_category=control_category).inc()
    except Exception:
        pass


def record_audit_log(event_type: str) -> None:
    """
    Record an audit log event.

    Args:
        event_type: Type of event ("login", "logout", "access_denied", etc.)
    """
    if not _metrics_available:
        return

    try:
        if _audit_logs_total:
            _audit_logs_total.labels(event_type=event_type).inc()
    except Exception:
        pass


def record_access_review_item(status: str) -> None:
    """
    Record an access review item.

    Args:
        status: Review status ("approved", "revoked", "pending")
    """
    if not _metrics_available:
        return

    try:
        if _access_review_items_total:
            _access_review_items_total.labels(status=status).inc()
    except Exception:
        pass


def record_compliance_job(job_type: str, status: str) -> None:
    """
    Record a compliance job execution.

    Args:
        job_type: Type of job ("daily_check", "weekly_access_review", etc.)
        status: Job status ("success", "failure")
    """
    if not _metrics_available:
        return

    try:
        if _compliance_job_executions_total:
            _compliance_job_executions_total.labels(job_type=job_type, status=status).inc()
    except Exception:
        pass


def record_compliance_report(report_type: str) -> None:
    """
    Record a compliance report generation.

    Args:
        report_type: Type of report ("daily", "weekly", "monthly")
    """
    if not _metrics_available:
        return

    try:
        if _compliance_report_generated_total:
            _compliance_report_generated_total.labels(report_type=report_type).inc()
    except Exception:
        pass


def record_gdpr_anonymization(count: int, operation: str = "audit_logs") -> None:
    """
    Record a GDPR anonymization operation.

    Args:
        count: Number of records anonymized
        operation: Type of operation ("audit_logs", "user_data", etc.)
    """
    if not _metrics_available:
        return

    try:
        if _gdpr_anonymization_total:
            _gdpr_anonymization_total.labels(operation=operation).inc(count)
    except Exception:
        pass


def record_gdpr_data_export(format: str, status: str) -> None:
    """
    Record a GDPR data export operation (DSAR - Article 15/20).

    Args:
        format: Export format ("json", "csv")
        status: Operation status ("success", "failure")
    """
    if not _metrics_available:
        return

    try:
        if _gdpr_data_export_total:
            _gdpr_data_export_total.labels(format=format, status=status).inc()
    except Exception:
        pass


def record_gdpr_data_deletion(operation: str, status: str) -> None:
    """
    Record a GDPR data deletion operation (Article 17 - Right to Erasure).

    Args:
        operation: Deletion operation type ("full", "sessions", "conversations", "preferences", "auth_tuples", "consents", "profile")
        status: Operation status ("success", "failure")
    """
    if not _metrics_available:
        return

    try:
        if _gdpr_data_deletion_total:
            _gdpr_data_deletion_total.labels(operation=operation, status=status).inc()
    except Exception:
        pass


def record_gdpr_retention_cleanup(data_type: str, status: str, count: int = 1) -> None:
    """
    Record a GDPR retention cleanup operation (Article 5 - Storage Limitation).

    Args:
        data_type: Type of data cleaned up ("sessions", "conversations", "audit_logs")
        status: Operation status ("success", "failure")
        count: Number of records cleaned up (default: 1)
    """
    if not _metrics_available:
        return

    try:
        if _gdpr_retention_cleanup_total:
            _gdpr_retention_cleanup_total.labels(data_type=data_type, status=status).inc(count)
    except Exception:
        pass
