"""
Background Agents API Router.

Provides endpoints for managing background AI agent tasks.

Phase 3.2: canvas_agents feature flag
- POST /api/v1/agents/background - Submit background task
- GET /api/v1/agents/background - List background tasks
- GET /api/v1/agents/background/{id} - Get task status
- DELETE /api/v1/agents/background/{id} - Cancel task

Usage:
    POST /api/v1/agents/background
    {
        "name": "Code Analysis Agent",
        "task": "Analyze code quality",
        "agent_type": "code_analysis",
        "data": {"directory": "src/"}
    }
"""

from __future__ import annotations

import logging
import uuid
from datetime import UTC, datetime
from typing import Annotated, Any

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from mcp_server_langgraph.auth.dependencies import get_current_user
from mcp_server_langgraph.core.feature_flags import feature_flags

logger = logging.getLogger(__name__)

# Type alias for authenticated user dependency
CurrentUser = Annotated[dict[str, Any], Depends(get_current_user)]

# Router
background_agents_router = APIRouter(prefix="/agents/background", tags=["background-agents"])


# =============================================================================
# Request/Response Models
# =============================================================================


class BackgroundTaskRequest(BaseModel):
    """Request model for submitting a background task."""

    name: str = Field(..., description="Human-readable name for the agent task")
    task: str = Field(..., description="Description of the task to perform")
    agent_type: str = Field(
        default="general",
        description="Type of agent (code_analysis, documentation, testing, etc.)",
    )
    data: dict[str, Any] = Field(
        default_factory=dict,
        description="Task-specific data and parameters",
    )
    priority: str = Field(
        default="normal",
        description="Task priority (low, normal, high)",
    )


class BackgroundTaskResponse(BaseModel):
    """Response model for a background task."""

    id: str = Field(..., description="Unique task identifier")
    name: str = Field(..., description="Human-readable name for the agent task")
    task: str = Field(..., description="Description of the task")
    status: str = Field(
        ...,
        description="Task status (queued, running, completed, failed, disabled, etc.)",
    )
    progress: int = Field(default=0, description="Progress percentage (0-100)")
    started_at: int = Field(..., description="Unix timestamp (milliseconds) when task was started")
    completed_at: int | None = Field(default=None, description="Unix timestamp when completed")
    error: str | None = Field(default=None, description="Error message if failed")
    artifacts: list[str] = Field(
        default_factory=list,
        description="List of artifact IDs generated by the task",
    )


class BackgroundTaskListResponse(BaseModel):
    """Response model for listing background tasks."""

    tasks: list[BackgroundTaskResponse] = Field(
        default_factory=list,
        description="List of background tasks",
    )
    total_count: int = Field(default=0, description="Total number of tasks")


class CancelTaskResponse(BaseModel):
    """Response model for canceling a task."""

    success: bool = Field(..., description="Whether cancellation was successful")
    message: str = Field(default="", description="Status message")
    task_id: str | None = Field(default=None, description="ID of the canceled task")


# =============================================================================
# In-Memory Task Storage (for now)
# =============================================================================

# In production, this would be backed by Redis or a database
_tasks: dict[str, BackgroundTaskResponse] = {}


def _get_current_timestamp_ms() -> int:
    """Get current Unix timestamp in milliseconds."""
    return int(datetime.now(UTC).timestamp() * 1000)


# =============================================================================
# API Endpoints
# =============================================================================


@background_agents_router.post(
    "",
    response_model=BackgroundTaskResponse,
    summary="Submit a background agent task",
    description="""
    Submit a new background agent task for asynchronous execution.

    The task will be queued and executed by the appropriate agent type.
    Returns immediately with a task ID for status tracking.
    """,
)
async def submit_background_task(
    request: BackgroundTaskRequest,
    current_user: CurrentUser,
) -> BackgroundTaskResponse:
    """
    Submit a new background task.

    Args:
        request: Task submission request
        current_user: Authenticated user context

    Returns:
        BackgroundTaskResponse with task ID and initial status
    """
    # Check feature flag - graceful degradation if disabled
    if not feature_flags.canvas_agents:
        logger.info("canvas_agents feature disabled, returning disabled status")
        return BackgroundTaskResponse(
            id=str(uuid.uuid4()),
            name=request.name,
            task=request.task,
            status="disabled",
            progress=0,
            started_at=_get_current_timestamp_ms(),
            error="Background agents feature is disabled",
        )

    # Create task entry
    task_id = str(uuid.uuid4())
    task = BackgroundTaskResponse(
        id=task_id,
        name=request.name,
        task=request.task,
        status="queued",
        progress=0,
        started_at=_get_current_timestamp_ms(),
    )

    # Store task (in production, queue to worker)
    _tasks[task_id] = task

    logger.info(
        f"Background task submitted: id={task_id}, name={request.name}",
        extra={
            "task_id": task_id,
            "agent_type": request.agent_type,
            "user_id": current_user.get("sub"),
        },
    )

    return task


@background_agents_router.get(
    "",
    response_model=BackgroundTaskListResponse,
    summary="List background tasks",
    description="Get a list of all background tasks for the current user.",
)
async def list_background_tasks(
    current_user: CurrentUser,
) -> BackgroundTaskListResponse:
    """
    List all background tasks.

    Args:
        current_user: Authenticated user context

    Returns:
        BackgroundTaskListResponse with list of tasks
    """
    # Check feature flag - return empty list if disabled
    if not feature_flags.canvas_agents:
        return BackgroundTaskListResponse(tasks=[], total_count=0)

    # In production, filter by user
    tasks = list(_tasks.values())

    return BackgroundTaskListResponse(
        tasks=tasks,
        total_count=len(tasks),
    )


@background_agents_router.get(
    "/{task_id}",
    response_model=BackgroundTaskResponse | None,
    summary="Get background task status",
    description="Get the status of a specific background task.",
)
async def get_background_task(
    task_id: str,
    current_user: CurrentUser,
) -> BackgroundTaskResponse | None:
    """
    Get a specific background task by ID.

    Args:
        task_id: Task identifier
        current_user: Authenticated user context

    Returns:
        BackgroundTaskResponse if found, None otherwise
    """
    # Check feature flag
    if not feature_flags.canvas_agents:
        return None

    return _tasks.get(task_id)


@background_agents_router.delete(
    "/{task_id}",
    response_model=CancelTaskResponse,
    summary="Cancel a background task",
    description="Cancel a queued or running background task.",
)
async def cancel_background_task(
    task_id: str,
    current_user: CurrentUser,
) -> CancelTaskResponse:
    """
    Cancel a background task.

    Args:
        task_id: Task identifier
        current_user: Authenticated user context

    Returns:
        CancelTaskResponse with success status
    """
    # Check feature flag
    if not feature_flags.canvas_agents:
        return CancelTaskResponse(
            success=False,
            message="Background agents feature is disabled",
        )

    task = _tasks.get(task_id)
    if not task:
        return CancelTaskResponse(
            success=False,
            message=f"Task not found: {task_id}",
        )

    # Only cancel if queued or running
    if task.status in ("queued", "running"):
        task.status = "failed"
        task.error = "Cancelled by user"
        task.completed_at = _get_current_timestamp_ms()

        logger.info(
            f"Background task cancelled: id={task_id}",
            extra={
                "task_id": task_id,
                "user_id": current_user.get("sub"),
            },
        )

        return CancelTaskResponse(
            success=True,
            message="Task cancelled successfully",
            task_id=task_id,
        )

    return CancelTaskResponse(
        success=False,
        message=f"Cannot cancel task with status: {task.status}",
        task_id=task_id,
    )
