"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.models.body_create_group_scim_v2_groups_post import BodyCreateGroupScimV2GroupsPost


class TestBodyCreateGroupScimV2GroupsPost(unittest.TestCase):
    """BodyCreateGroupScimV2GroupsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyCreateGroupScimV2GroupsPost:
        """Test BodyCreateGroupScimV2GroupsPost
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BodyCreateGroupScimV2GroupsPost`
        """
        model = BodyCreateGroupScimV2GroupsPost()
        if include_optional:
            return BodyCreateGroupScimV2GroupsPost(
                group_data = { },
                credentials = mcp_client.models.http_authorization_credentials.HTTPAuthorizationCredentials(
                    scheme = '',
                    credentials = '', )
            )
        else:
            return BodyCreateGroupScimV2GroupsPost(
                group_data = { },
        )
        """

    def testBodyCreateGroupScimV2GroupsPost(self):
        """Test BodyCreateGroupScimV2GroupsPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
