"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.api.api_metadata_api import APIMetadataApi


class TestAPIMetadataApi(unittest.TestCase):
    """APIMetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIMetadataApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_version_metadata(self) -> None:
        """Test case for get_api_version_metadata

        Get API version information
        """
        pass


if __name__ == "__main__":
    unittest.main()
