# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.body_update_consent_api_v1_users_me_consent_post import BodyUpdateConsentApiV1UsersMeConsentPost


class TestBodyUpdateConsentApiV1UsersMeConsentPost(unittest.TestCase):
    """BodyUpdateConsentApiV1UsersMeConsentPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyUpdateConsentApiV1UsersMeConsentPost:
        """Test BodyUpdateConsentApiV1UsersMeConsentPost
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BodyUpdateConsentApiV1UsersMeConsentPost`
        """
        model = BodyUpdateConsentApiV1UsersMeConsentPost()
        if include_optional:
            return BodyUpdateConsentApiV1UsersMeConsentPost(
                consent = {consent_type=analytics, granted=true},
                credentials = mcp_client.models.http_authorization_credentials.HTTPAuthorizationCredentials(
                    scheme = '',
                    credentials = '', )
            )
        else:
            return BodyUpdateConsentApiV1UsersMeConsentPost(
                consent = {consent_type=analytics, granted=true},
        )
        """

    def testBodyUpdateConsentApiV1UsersMeConsentPost(self):
        """Test BodyUpdateConsentApiV1UsersMeConsentPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
