# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.api_version_info import APIVersionInfo

class TestAPIVersionInfo(unittest.TestCase):
    """APIVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIVersionInfo:
        """Test APIVersionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIVersionInfo`
        """
        model = APIVersionInfo()
        if include_optional:
            return APIVersionInfo(
                version = '',
                api_version = '',
                supported_versions = [
                    ''
                    ],
                deprecated_versions = [
                    ''
                    ],
                sunset_dates = {
                    'key' : ''
                    },
                changelog_url = '',
                documentation_url = ''
            )
        else:
            return APIVersionInfo(
                version = '',
                api_version = '',
                supported_versions = [
                    ''
                    ],
        )
        """

    def testAPIVersionInfo(self):
        """Test APIVersionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
