"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.models.create_service_principal_response import CreateServicePrincipalResponse


class TestCreateServicePrincipalResponse(unittest.TestCase):
    """CreateServicePrincipalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateServicePrincipalResponse:
        """Test CreateServicePrincipalResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateServicePrincipalResponse`
        """
        model = CreateServicePrincipalResponse()
        if include_optional:
            return CreateServicePrincipalResponse(
                service_id = '',
                name = '',
                description = '',
                authentication_mode = '',
                associated_user_id = '',
                owner_user_id = '',
                inherit_permissions = True,
                enabled = True,
                created_at = '',
                client_secret = '',
                message = 'Service principal created successfully. Save the client_secret securely.'
            )
        else:
            return CreateServicePrincipalResponse(
                service_id = '',
                name = '',
                description = '',
                authentication_mode = '',
                associated_user_id = '',
                owner_user_id = '',
                inherit_permissions = True,
                enabled = True,
                created_at = '',
                client_secret = '',
        )
        """

    def testCreateServicePrincipalResponse(self):
        """Test CreateServicePrincipalResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
