"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.api.service_principals_api import ServicePrincipalsApi


class TestServicePrincipalsApi(unittest.TestCase):
    """ServicePrincipalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicePrincipalsApi()

    def tearDown(self) -> None:
        pass

    def test_associate_service_principal_with_user_api_v1_service_principals_service_id_associate_user_post(self) -> None:
        """Test case for associate_service_principal_with_user_api_v1_service_principals_service_id_associate_user_post

        Associate Service Principal With User
        """
        pass

    def test_create_service_principal_api_v1_service_principals_post(self) -> None:
        """Test case for create_service_principal_api_v1_service_principals_post

        Create Service Principal
        """
        pass

    def test_delete_service_principal_api_v1_service_principals_service_id_delete(self) -> None:
        """Test case for delete_service_principal_api_v1_service_principals_service_id_delete

        Delete Service Principal
        """
        pass

    def test_get_service_principal_api_v1_service_principals_service_id_get(self) -> None:
        """Test case for get_service_principal_api_v1_service_principals_service_id_get

        Get Service Principal
        """
        pass

    def test_list_service_principals_api_v1_service_principals_get(self) -> None:
        """Test case for list_service_principals_api_v1_service_principals_get

        List Service Principals
        """
        pass

    def test_rotate_service_principal_secret_api_v1_service_principals_service_id_rotate_secret_post(self) -> None:
        """Test case for rotate_service_principal_secret_api_v1_service_principals_service_id_rotate_secret_post

        Rotate Service Principal Secret
        """
        pass


if __name__ == "__main__":
    unittest.main()
