# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.body_update_user_profile_api_v1_users_me_patch import BodyUpdateUserProfileApiV1UsersMePatch


class TestBodyUpdateUserProfileApiV1UsersMePatch(unittest.TestCase):
    """BodyUpdateUserProfileApiV1UsersMePatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyUpdateUserProfileApiV1UsersMePatch:
        """Test BodyUpdateUserProfileApiV1UsersMePatch
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BodyUpdateUserProfileApiV1UsersMePatch`
        """
        model = BodyUpdateUserProfileApiV1UsersMePatch()
        if include_optional:
            return BodyUpdateUserProfileApiV1UsersMePatch(
                profile_update = {"email":"alice.smith@acme.com","name":"Alice Smith","preferences":{"language":"en","theme":"dark"}},
                credentials = mcp_client.models.http_authorization_credentials.HTTPAuthorizationCredentials(
                    scheme = '',
                    credentials = '', )
            )
        else:
            return BodyUpdateUserProfileApiV1UsersMePatch(
                profile_update = {"email":"alice.smith@acme.com","name":"Alice Smith","preferences":{"language":"en","theme":"dark"}},
        )
        """

    def testBodyUpdateUserProfileApiV1UsersMePatch(self):
        """Test BodyUpdateUserProfileApiV1UsersMePatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
