# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.body_create_api_key_api_v1_api_keys_post import BodyCreateApiKeyApiV1ApiKeysPost

class TestBodyCreateApiKeyApiV1ApiKeysPost(unittest.TestCase):
    """BodyCreateApiKeyApiV1ApiKeysPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyCreateApiKeyApiV1ApiKeysPost:
        """Test BodyCreateApiKeyApiV1ApiKeysPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyCreateApiKeyApiV1ApiKeysPost`
        """
        model = BodyCreateApiKeyApiV1ApiKeysPost()
        if include_optional:
            return BodyCreateApiKeyApiV1ApiKeysPost(
                request = mcp_client.models.create_api_key_request.CreateAPIKeyRequest(
                    name = '', 
                    expires_days = 56, ),
                credentials = mcp_client.models.http_authorization_credentials.HTTPAuthorizationCredentials(
                    scheme = '', 
                    credentials = '', )
            )
        else:
            return BodyCreateApiKeyApiV1ApiKeysPost(
                request = mcp_client.models.create_api_key_request.CreateAPIKeyRequest(
                    name = '', 
                    expires_days = 56, ),
        )
        """

    def testBodyCreateApiKeyApiV1ApiKeysPost(self):
        """Test BodyCreateApiKeyApiV1ApiKeysPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
