"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.models.scim_patch_request import SCIMPatchRequest


class TestSCIMPatchRequest(unittest.TestCase):
    """SCIMPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SCIMPatchRequest:
        """Test SCIMPatchRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SCIMPatchRequest`
        """
        model = SCIMPatchRequest()
        if include_optional:
            return SCIMPatchRequest(
                schemas = [
                    ''
                    ],
                operations = [
                    mcp_client.models.scim_patch_operation.SCIMPatchOperation(
                        op = 'add',
                        path = '',
                        value = null, )
                    ]
            )
        else:
            return SCIMPatchRequest(
                operations = [
                    mcp_client.models.scim_patch_operation.SCIMPatchOperation(
                        op = 'add',
                        path = '',
                        value = null, )
                    ],
        )
        """

    def testSCIMPatchRequest(self):
        """Test SCIMPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
