"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.models.service_principal_response import ServicePrincipalResponse


class TestServicePrincipalResponse(unittest.TestCase):
    """ServicePrincipalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicePrincipalResponse:
        """Test ServicePrincipalResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ServicePrincipalResponse`
        """
        model = ServicePrincipalResponse()
        if include_optional:
            return ServicePrincipalResponse(
                service_id = '',
                name = '',
                description = '',
                authentication_mode = '',
                associated_user_id = '',
                owner_user_id = '',
                inherit_permissions = True,
                enabled = True,
                created_at = ''
            )
        else:
            return ServicePrincipalResponse(
                service_id = '',
                name = '',
                description = '',
                authentication_mode = '',
                associated_user_id = '',
                owner_user_id = '',
                inherit_permissions = True,
                enabled = True,
                created_at = '',
        )
        """

    def testServicePrincipalResponse(self):
        """Test ServicePrincipalResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
