# coding: utf-8

"""
    MCP Server with LangGraph

    AI Agent with fine-grained authorization and observability - StreamableHTTP transport

    The version of the OpenAPI document: 2.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.scim_group_membership import SCIMGroupMembership

class TestSCIMGroupMembership(unittest.TestCase):
    """SCIMGroupMembership unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SCIMGroupMembership:
        """Test SCIMGroupMembership
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SCIMGroupMembership`
        """
        model = SCIMGroupMembership()
        if include_optional:
            return SCIMGroupMembership(
                value = '',
                ref = '',
                display = '',
                type = ''
            )
        else:
            return SCIMGroupMembership(
                value = '',
        )
        """

    def testSCIMGroupMembership(self):
        """Test SCIMGroupMembership"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
