"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from mcp_client.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_key_api_v1_api_keys_post(self) -> None:
        """Test case for create_api_key_api_v1_api_keys_post

        Create Api Key
        """
        pass

    def test_list_api_keys_api_v1_api_keys_get(self) -> None:
        """Test case for list_api_keys_api_v1_api_keys_get

        List Api Keys
        """
        pass

    def test_revoke_api_key_api_v1_api_keys_key_id_delete(self) -> None:
        """Test case for revoke_api_key_api_v1_api_keys_key_id_delete

        Revoke Api Key
        """
        pass

    def test_rotate_api_key_api_v1_api_keys_key_id_rotate_post(self) -> None:
        """Test case for rotate_api_key_api_v1_api_keys_key_id_rotate_post

        Rotate Api Key
        """
        pass


if __name__ == "__main__":
    unittest.main()
