# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.7.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_server_langgraph_client.api.mcp_api import McpApi


class TestMcpApi(unittest.TestCase):
    """McpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = McpApi()

    def tearDown(self) -> None:
        pass

    def test_handle_message_message_post(self) -> None:
        """Test case for handle_message_message_post

        Handle Message
        """
        pass

    def test_list_resources_resources_get(self) -> None:
        """Test case for list_resources_resources_get

        List Resources
        """
        pass

    def test_list_tools_tools_get(self) -> None:
        """Test case for list_tools_tools_get

        List Tools
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == "__main__":
    unittest.main()
