# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.body_update_user_scim_v2_users_user_id_patch import BodyUpdateUserScimV2UsersUserIdPatch


class TestBodyUpdateUserScimV2UsersUserIdPatch(unittest.TestCase):
    """BodyUpdateUserScimV2UsersUserIdPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyUpdateUserScimV2UsersUserIdPatch:
        """Test BodyUpdateUserScimV2UsersUserIdPatch
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BodyUpdateUserScimV2UsersUserIdPatch`
        """
        model = BodyUpdateUserScimV2UsersUserIdPatch()
        if include_optional:
            return BodyUpdateUserScimV2UsersUserIdPatch(
                patch_request = mcp_client.models.scim_patch_request.SCIMPatchRequest(
                    schemas = [
                        ''
                        ],
                    operations = [
                        mcp_client.models.scim_patch_operation.SCIMPatchOperation(
                            op = 'add',
                            path = '',
                            value = null, )
                        ], ),
                credentials = mcp_client.models.http_authorization_credentials.HTTPAuthorizationCredentials(
                    scheme = '',
                    credentials = '', )
            )
        else:
            return BodyUpdateUserScimV2UsersUserIdPatch(
                patch_request = mcp_client.models.scim_patch_request.SCIMPatchRequest(
                    schemas = [
                        ''
                        ],
                    operations = [
                        mcp_client.models.scim_patch_operation.SCIMPatchOperation(
                            op = 'add',
                            path = '',
                            value = null, )
                        ], ),
        )
        """

    def testBodyUpdateUserScimV2UsersUserIdPatch(self):
        """Test BodyUpdateUserScimV2UsersUserIdPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
