# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.consent_response import ConsentResponse


class TestConsentResponse(unittest.TestCase):
    """ConsentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsentResponse:
        """Test ConsentResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConsentResponse`
        """
        model = ConsentResponse()
        if include_optional:
            return ConsentResponse(
                user_id = '',
                consents = {
                    'key' : { }
                    }
            )
        else:
            return ConsentResponse(
                user_id = '',
                consents = {
                    'key' : { }
                    },
        )
        """

    def testConsentResponse(self):
        """Test ConsentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
