# coding: utf-8

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from mcp_client.models.body_create_service_principal_api_v1_service_principals_post import (
    BodyCreateServicePrincipalApiV1ServicePrincipalsPost,
)


class TestBodyCreateServicePrincipalApiV1ServicePrincipalsPost(unittest.TestCase):
    """BodyCreateServicePrincipalApiV1ServicePrincipalsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyCreateServicePrincipalApiV1ServicePrincipalsPost:
        """Test BodyCreateServicePrincipalApiV1ServicePrincipalsPost
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BodyCreateServicePrincipalApiV1ServicePrincipalsPost`
        """
        model = BodyCreateServicePrincipalApiV1ServicePrincipalsPost()
        if include_optional:
            return BodyCreateServicePrincipalApiV1ServicePrincipalsPost(
                request = mcp_client.models.create_service_principal_request.CreateServicePrincipalRequest(
                    name = '',
                    description = '',
                    authentication_mode = 'client_credentials',
                    associated_user_id = '',
                    inherit_permissions = True, ),
                credentials = mcp_client.models.http_authorization_credentials.HTTPAuthorizationCredentials(
                    scheme = '',
                    credentials = '', )
            )
        else:
            return BodyCreateServicePrincipalApiV1ServicePrincipalsPost(
                request = mcp_client.models.create_service_principal_request.CreateServicePrincipalRequest(
                    name = '',
                    description = '',
                    authentication_mode = 'client_credentials',
                    associated_user_id = '',
                    inherit_permissions = True, ),
        )
        """

    def testBodyCreateServicePrincipalApiV1ServicePrincipalsPost(self):
        """Test BodyCreateServicePrincipalApiV1ServicePrincipalsPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
