/**
 * HITL (Human-in-the-Loop) Type Definitions
 *
 * Consolidated types for agent approval and clarification flows.
 * These types are used across:
 * - WebSocket payloads (useAgentRequestWebSocket)
 * - UI components (AgentApprovalDialog, ClarificationDialog)
 * - State management hooks (useHITLDialogs)
 *
 * Type naming convention:
 * - *Request: Data describing what the agent is asking for
 * - *Response: Data the user sends back
 * - *Payload: WebSocket message data
 * - UI suffix: Types used in UI layer
 * - API suffix: Types used in API/hook layer
 */

// =============================================================================
// AI Explanation Types (AI-Native HITL Enhancements Phase 1)
// =============================================================================

/**
 * Individual factor contributing to confidence score.
 *
 * Represents a single piece of evidence that either increases or
 * decreases the agent's confidence in its proposed action.
 */
export interface ConfidenceFactor {
  /** Factor name (e.g., "ambiguous_input", "multiple_interpretations") */
  factor: string;
  /** Impact on confidence (-1.0 to 1.0, negative reduces confidence) */
  weight: number;
  /** Supporting evidence or reasoning for this factor */
  evidence: string;
}

/**
 * Safer alternative action the agent could take.
 *
 * Represents an alternative approach with expected confidence and
 * trade-offs, helping users make informed decisions.
 */
export interface AlternativeSuggestion {
  /** Description of the alternative action */
  action: string;
  /** Expected confidence if this action is taken (0.0 to 1.0) */
  confidence: number;
  /** What the user gives up by choosing this alternative */
  trade_off: string;
}

/**
 * AI-generated explanation for HITL approval requests.
 *
 * Provides rich, context-aware explanations generated by the
 * ExplanationOrchestrator using parallel analysis agents.
 *
 * Core Explanation:
 *   - why_uncertain: Natural language explanation of uncertainty
 *   - what_could_go_wrong: Risk analysis of potential issues
 *   - safer_alternatives: List of safer options with trade-offs
 *
 * Supporting Evidence:
 *   - confidence_factors: Factors affecting confidence score
 *   - reasoning_trace: Key steps in the agent's reasoning
 *
 * Metadata:
 *   - model_used: LLM model that generated the explanation
 *   - generated_at: Timestamp of generation
 *   - generation_latency_ms: Time taken to generate
 *   - cached: Whether explanation was retrieved from cache
 */
export interface AIExplanation {
  /** Natural language explanation of why the agent is uncertain */
  why_uncertain: string;
  /** Risk analysis of potential negative outcomes */
  what_could_go_wrong: string;
  /** List of safer alternative actions (optional) */
  safer_alternatives?: AlternativeSuggestion[];
  /** Factors affecting the confidence score (optional) */
  confidence_factors?: ConfidenceFactor[];
  /** Key steps in the agent's reasoning process (optional) */
  reasoning_trace?: string[];
  /** LLM model used to generate the explanation (optional) */
  model_used?: string;
  /** Timestamp when explanation was generated (optional) */
  generated_at?: string;
  /** Time taken to generate explanation in milliseconds (optional) */
  generation_latency_ms?: number;
  /** Whether explanation was retrieved from cache (optional) */
  cached?: boolean;
}

// =============================================================================
// Clarification Option Types
// =============================================================================

/**
 * Option in a multiple-choice clarification request
 */
export interface ClarificationOption {
  id: string;
  label: string;
  description?: string;
  is_recommended?: boolean;
}

// =============================================================================
// Agent Request Types (What the agent asks for)
// =============================================================================

/**
 * Approval request from an agent requiring human decision
 */
export interface AgentApprovalRequest {
  request_id: string;
  session_id: string;
  task_id: string;
  agent_name: string;
  confidence: number;
  threshold: number;
  proposed_action: string;
  trigger_reason: string;
  context: {
    tokens_used?: number;
    time_elapsed_seconds?: number;
    artifacts?: string[];
    [key: string]: unknown;
  };
  requested_at: string;
  /** AI-generated explanation for HITL dialog (Phase 1 AI-Native Enhancement) */
  ai_explanation?: AIExplanation;
}

/**
 * Clarification request from an agent requiring human input
 */
export interface AgentClarificationRequest {
  request_id: string;
  session_id: string;
  task_id: string;
  agent_name: string;
  clarification_type: "text" | "choice" | "confirmation";
  question: string;
  options: ClarificationOption[];
  placeholder: string | null;
  required: boolean;
  context: Record<string, unknown>;
  requested_at: string;
}

// =============================================================================
// Response Types (What the user sends back)
// =============================================================================

/**
 * UI-layer clarification response (used by ClarificationDialog component)
 *
 * This format is optimized for the dialog UI:
 * - Uses `value` for text input
 * - Uses `selected_option_id` for choice
 * - Includes `responded_by` for attribution
 */
export interface ClarificationUIResponse {
  request_id: string;
  value?: string;
  selected_option_id?: string;
  confirmed?: boolean;
  responded_by: string;
}

/**
 * API-layer clarification response (used by useHITLDialogs hook for API calls)
 *
 * This format matches the backend API contract:
 * - Explicit `response_type` discriminator
 * - Uses `text_response` for text input
 * - Uses `selected_option` for choice
 */
export interface ClarificationAPIResponse {
  request_id: string;
  response_type: "choice" | "text" | "confirm";
  selected_option?: string;
  text_response?: string;
  confirmed?: boolean;
}

/**
 * Approval response from user
 */
export interface ApprovalResponse {
  request_id: string;
  approved: boolean;
  approved_by: string;
  reason?: string;
  modifications?: Record<string, unknown>;
}

// =============================================================================
// WebSocket Payload Types
// =============================================================================

/**
 * WebSocket payload for approval required messages
 */
export interface ApprovalRequiredPayload {
  request_id: string;
  session_id: string;
  task_id: string;
  agent_name: string;
  confidence: number;
  threshold: number;
  proposed_action: string;
  trigger_reason: string;
  context: Record<string, unknown>;
  requested_at: string;
  /** AI-generated explanation for HITL dialog (Phase 1 AI-Native Enhancement) */
  ai_explanation?: AIExplanation;
}

/**
 * WebSocket payload for clarification required messages
 */
export interface ClarificationRequiredPayload {
  request_id: string;
  session_id: string;
  task_id: string;
  agent_name: string;
  clarification_type: "text" | "choice" | "confirmation";
  question: string;
  options: ClarificationOption[];
  placeholder: string | null;
  required: boolean;
  context: Record<string, unknown>;
  requested_at: string;
}

// =============================================================================
// Type Conversion Utilities
// =============================================================================

/**
 * Convert UI response format to API response format
 *
 * The UI dialog uses a simpler format where the response type is inferred
 * from which fields are populated. The API requires an explicit response_type.
 *
 * Priority: confirmed > selected_option_id > value (text)
 *
 * @param uiResponse - Response from ClarificationDialog component
 * @returns Response formatted for the API
 */
export function convertUIResponseToAPIResponse(
  uiResponse: ClarificationUIResponse
): ClarificationAPIResponse {
  // Determine response type based on which fields are set
  // Priority: confirmed > choice > text
  if (uiResponse.confirmed !== undefined) {
    return {
      request_id: uiResponse.request_id,
      response_type: "confirm",
      confirmed: uiResponse.confirmed,
    };
  }

  if (uiResponse.selected_option_id) {
    return {
      request_id: uiResponse.request_id,
      response_type: "choice",
      selected_option: uiResponse.selected_option_id,
    };
  }

  // Default to text
  return {
    request_id: uiResponse.request_id,
    response_type: "text",
    text_response: uiResponse.value,
  };
}

/**
 * Convert API response format to UI response format
 *
 * Useful for displaying API responses in the UI or for testing.
 *
 * @param apiResponse - Response from API
 * @param respondedBy - User who responded (required for UI format)
 * @returns Response formatted for UI display
 */
export function convertAPIResponseToUIResponse(
  apiResponse: ClarificationAPIResponse,
  respondedBy: string
): ClarificationUIResponse {
  const base: ClarificationUIResponse = {
    request_id: apiResponse.request_id,
    responded_by: respondedBy,
  };

  switch (apiResponse.response_type) {
    case "text":
      return { ...base, value: apiResponse.text_response };
    case "choice":
      return { ...base, selected_option_id: apiResponse.selected_option };
    case "confirm":
      return { ...base, confirmed: apiResponse.confirmed };
    default:
      return base;
  }
}

// =============================================================================
// Payload Conversion Utilities
// =============================================================================

/**
 * Convert WebSocket approval payload to dialog request format
 */
export function convertApprovalPayloadToRequest(
  payload: ApprovalRequiredPayload
): AgentApprovalRequest {
  return {
    request_id: payload.request_id,
    session_id: payload.session_id,
    task_id: payload.task_id,
    agent_name: payload.agent_name,
    confidence: payload.confidence,
    threshold: payload.threshold,
    proposed_action: payload.proposed_action,
    trigger_reason: payload.trigger_reason,
    context: payload.context as AgentApprovalRequest["context"],
    requested_at: payload.requested_at,
    ai_explanation: payload.ai_explanation,
  };
}

/**
 * Convert WebSocket clarification payload to dialog request format
 */
export function convertClarificationPayloadToRequest(
  payload: ClarificationRequiredPayload
): AgentClarificationRequest {
  return {
    request_id: payload.request_id,
    session_id: payload.session_id,
    task_id: payload.task_id,
    agent_name: payload.agent_name,
    clarification_type: payload.clarification_type,
    question: payload.question,
    options: payload.options,
    placeholder: payload.placeholder,
    required: payload.required,
    context: payload.context,
    requested_at: payload.requested_at,
  };
}
