# coding: utf-8

# flake8: noqa

"""
MCP Server with LangGraph

AI Agent with fine-grained authorization and observability - StreamableHTTP transport

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "2.8.0"

# Define package exports
__all__ = [
    "APIKeysApi",
    "APIMetadataApi",
    "GDPRComplianceApi",
    "SCIM20Api",
    "ServicePrincipalsApi",
    "AuthApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIKeyResponse",
    "APIVersionInfo",
    "BodyCreateApiKeyApiV1ApiKeysPost",
    "BodyCreateGroupScimV2GroupsPost",
    "BodyCreateServicePrincipalApiV1ServicePrincipalsPost",
    "BodyCreateUserScimV2UsersPost",
    "BodyReplaceUserScimV2UsersUserIdPut",
    "BodyUpdateConsentApiV1UsersMeConsentPost",
    "BodyUpdateUserProfileApiV1UsersMePatch",
    "BodyUpdateUserScimV2UsersUserIdPatch",
    "ConsentRecord",
    "ConsentResponse",
    "ConsentType",
    "CreateAPIKeyRequest",
    "CreateAPIKeyResponse",
    "CreateServicePrincipalRequest",
    "CreateServicePrincipalResponse",
    "HTTPAuthorizationCredentials",
    "HTTPValidationError",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RotateAPIKeyResponse",
    "RotateSecretResponse",
    "SCIMAddress",
    "SCIMEmail",
    "SCIMEnterpriseUser",
    "SCIMGroup",
    "SCIMGroupMembership",
    "SCIMListResponse",
    "SCIMMember",
    "SCIMName",
    "SCIMPatchOp",
    "SCIMPatchOperation",
    "SCIMPatchRequest",
    "SCIMPhoneNumber",
    "SCIMUser",
    "ServicePrincipalResponse",
    "UserDataExport",
    "UserProfileUpdate",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from mcp_client.api.api_keys_api import APIKeysApi as APIKeysApi
from mcp_client.api.api_metadata_api import APIMetadataApi as APIMetadataApi
from mcp_client.api.auth_api import AuthApi as AuthApi
from mcp_client.api.default_api import DefaultApi as DefaultApi
from mcp_client.api.gdpr_compliance_api import GDPRComplianceApi as GDPRComplianceApi
from mcp_client.api.scim20_api import SCIM20Api as SCIM20Api
from mcp_client.api.service_principals_api import ServicePrincipalsApi as ServicePrincipalsApi
from mcp_client.api_client import ApiClient as ApiClient

# import ApiClient
from mcp_client.api_response import ApiResponse as ApiResponse
from mcp_client.configuration import Configuration as Configuration
from mcp_client.exceptions import ApiAttributeError as ApiAttributeError
from mcp_client.exceptions import ApiException as ApiException
from mcp_client.exceptions import ApiKeyError as ApiKeyError
from mcp_client.exceptions import ApiTypeError as ApiTypeError
from mcp_client.exceptions import ApiValueError as ApiValueError
from mcp_client.exceptions import OpenApiException as OpenApiException

# import models into sdk package
from mcp_client.models.api_key_response import APIKeyResponse as APIKeyResponse
from mcp_client.models.api_version_info import APIVersionInfo as APIVersionInfo
from mcp_client.models.body_create_api_key_api_v1_api_keys_post import (
    BodyCreateApiKeyApiV1ApiKeysPost as BodyCreateApiKeyApiV1ApiKeysPost,
)
from mcp_client.models.body_create_group_scim_v2_groups_post import (
    BodyCreateGroupScimV2GroupsPost as BodyCreateGroupScimV2GroupsPost,
)
from mcp_client.models.body_create_service_principal_api_v1_service_principals_post import (
    BodyCreateServicePrincipalApiV1ServicePrincipalsPost as BodyCreateServicePrincipalApiV1ServicePrincipalsPost,
)
from mcp_client.models.body_create_user_scim_v2_users_post import (
    BodyCreateUserScimV2UsersPost as BodyCreateUserScimV2UsersPost,
)
from mcp_client.models.body_replace_user_scim_v2_users_user_id_put import (
    BodyReplaceUserScimV2UsersUserIdPut as BodyReplaceUserScimV2UsersUserIdPut,
)
from mcp_client.models.body_update_consent_api_v1_users_me_consent_post import (
    BodyUpdateConsentApiV1UsersMeConsentPost as BodyUpdateConsentApiV1UsersMeConsentPost,
)
from mcp_client.models.body_update_user_profile_api_v1_users_me_patch import (
    BodyUpdateUserProfileApiV1UsersMePatch as BodyUpdateUserProfileApiV1UsersMePatch,
)
from mcp_client.models.body_update_user_scim_v2_users_user_id_patch import (
    BodyUpdateUserScimV2UsersUserIdPatch as BodyUpdateUserScimV2UsersUserIdPatch,
)
from mcp_client.models.consent_record import ConsentRecord as ConsentRecord
from mcp_client.models.consent_response import ConsentResponse as ConsentResponse
from mcp_client.models.consent_type import ConsentType as ConsentType
from mcp_client.models.create_api_key_request import CreateAPIKeyRequest as CreateAPIKeyRequest
from mcp_client.models.create_api_key_response import CreateAPIKeyResponse as CreateAPIKeyResponse
from mcp_client.models.create_service_principal_request import CreateServicePrincipalRequest as CreateServicePrincipalRequest
from mcp_client.models.create_service_principal_response import (
    CreateServicePrincipalResponse as CreateServicePrincipalResponse,
)
from mcp_client.models.http_authorization_credentials import HTTPAuthorizationCredentials as HTTPAuthorizationCredentials
from mcp_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from mcp_client.models.login_request import LoginRequest as LoginRequest
from mcp_client.models.login_response import LoginResponse as LoginResponse
from mcp_client.models.refresh_token_request import RefreshTokenRequest as RefreshTokenRequest
from mcp_client.models.refresh_token_response import RefreshTokenResponse as RefreshTokenResponse
from mcp_client.models.rotate_api_key_response import RotateAPIKeyResponse as RotateAPIKeyResponse
from mcp_client.models.rotate_secret_response import RotateSecretResponse as RotateSecretResponse
from mcp_client.models.scim_address import SCIMAddress as SCIMAddress
from mcp_client.models.scim_email import SCIMEmail as SCIMEmail
from mcp_client.models.scim_enterprise_user import SCIMEnterpriseUser as SCIMEnterpriseUser
from mcp_client.models.scim_group import SCIMGroup as SCIMGroup
from mcp_client.models.scim_group_membership import SCIMGroupMembership as SCIMGroupMembership
from mcp_client.models.scim_list_response import SCIMListResponse as SCIMListResponse
from mcp_client.models.scim_member import SCIMMember as SCIMMember
from mcp_client.models.scim_name import SCIMName as SCIMName
from mcp_client.models.scim_patch_op import SCIMPatchOp as SCIMPatchOp
from mcp_client.models.scim_patch_operation import SCIMPatchOperation as SCIMPatchOperation
from mcp_client.models.scim_patch_request import SCIMPatchRequest as SCIMPatchRequest
from mcp_client.models.scim_phone_number import SCIMPhoneNumber as SCIMPhoneNumber
from mcp_client.models.scim_user import SCIMUser as SCIMUser
from mcp_client.models.service_principal_response import ServicePrincipalResponse as ServicePrincipalResponse
from mcp_client.models.user_data_export import UserDataExport as UserDataExport
from mcp_client.models.user_profile_update import UserProfileUpdate as UserProfileUpdate
from mcp_client.models.validation_error import ValidationError as ValidationError
from mcp_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
