"""
Test that test infrastructure reports are fresh (< 7 days old).

This meta-test ensures that automated reports are regularly regenerated
and not stale.

Reports are generated by:
- make generate-reports (manual)
- .github/workflows/weekly-reports.yaml (automated, every Sunday)
"""

import gc
from datetime import datetime, timedelta
from pathlib import Path

import pytest


@pytest.mark.meta
@pytest.mark.xdist_group(name="testreportfreshness")
class TestReportFreshness:
    """Validate that test infrastructure reports are fresh."""

    def teardown_method(self):
        """Force GC to prevent mock accumulation in xdist workers"""
        gc.collect()

    def test_async_mock_scan_report_is_fresh(self):
        """
        GIVEN: AsyncMock scan report exists
        WHEN: Checking file modification time
        THEN: Should be < 7 days old
        """
        report_path = Path("docs-internal/reports/ASYNC_MOCK_SCAN.md")

        assert report_path.exists(), f"Report not found: {report_path}\\n" f"Fix: Run 'make generate-reports'"

        mtime = datetime.fromtimestamp(report_path.stat().st_mtime)
        age_days = (datetime.now() - mtime).days

        assert age_days < 7, (
            f"AsyncMock scan report is {age_days} days old (>7 days)\\n"
            f"Last modified: {mtime.strftime('%Y-%m-%d %H:%M:%S')}\\n"
            f"Fix: Run 'make generate-reports' to regenerate"
        )

    def test_memory_safety_scan_report_is_fresh(self):
        """
        GIVEN: Memory safety scan report exists
        WHEN: Checking file modification time
        THEN: Should be < 7 days old
        """
        report_path = Path("docs-internal/reports/MEMORY_SAFETY_SCAN.md")

        assert report_path.exists(), f"Report not found: {report_path}\\n" f"Fix: Run 'make generate-reports'"

        mtime = datetime.fromtimestamp(report_path.stat().st_mtime)
        age_days = (datetime.now() - mtime).days

        assert age_days < 7, (
            f"Memory safety scan report is {age_days} days old (>7 days)\\n"
            f"Last modified: {mtime.strftime('%Y-%m-%d %H:%M:%S')}\\n"
            f"Fix: Run 'make generate-reports' to regenerate"
        )

    def test_test_suite_stats_report_is_fresh(self):
        """
        GIVEN: Test suite statistics report exists
        WHEN: Checking file modification time
        THEN: Should be < 7 days old
        """
        report_path = Path("docs-internal/reports/TEST_SUITE_STATS.md")

        assert report_path.exists(), f"Report not found: {report_path}\\n" f"Fix: Run 'make generate-reports'"

        mtime = datetime.fromtimestamp(report_path.stat().st_mtime)
        age_days = (datetime.now() - mtime).days

        assert age_days < 7, (
            f"Test suite stats report is {age_days} days old (>7 days)\\n"
            f"Last modified: {mtime.strftime('%Y-%m-%d %H:%M:%S')}\\n"
            f"Fix: Run 'make generate-reports' to regenerate"
        )

    def test_all_reports_exist(self):
        """
        GIVEN: Reports automation is configured
        WHEN: Checking for expected reports
        THEN: All reports should exist
        """
        expected_reports = [
            "docs-internal/reports/ASYNC_MOCK_SCAN.md",
            "docs-internal/reports/MEMORY_SAFETY_SCAN.md",
            "docs-internal/reports/TEST_SUITE_STATS.md",
        ]

        missing_reports = []
        for report in expected_reports:
            if not Path(report).exists():
                missing_reports.append(report)

        assert not missing_reports, (
            f"Missing {len(missing_reports)} report(s):\\n"
            + "\\n".join(f"  - {r}" for r in missing_reports)
            + "\\n\\nFix: Run 'make generate-reports'"
        )

    def test_reports_directory_exists(self):
        """
        GIVEN: Reports automation is configured
        WHEN: Checking for reports directory
        THEN: Directory should exist
        """
        reports_dir = Path("docs-internal/reports")

        assert reports_dir.exists(), (
            f"Reports directory not found: {reports_dir}\\n" f"Fix: mkdir -p docs-internal/reports && make generate-reports"
        )

        assert reports_dir.is_dir(), f"Reports path exists but is not a directory: {reports_dir}"

    def test_weekly_reports_workflow_exists(self):
        """
        GIVEN: Automated report generation is configured
        WHEN: Checking for GitHub Actions workflow
        THEN: weekly-reports.yaml should exist
        """
        workflow_path = Path(".github/workflows/weekly-reports.yaml")

        assert workflow_path.exists(), (
            f"Weekly reports workflow not found: {workflow_path}\\n"
            f"Expected: Automated weekly report regeneration via GitHub Actions"
        )

    def test_generate_reports_makefile_target_exists(self):
        """
        GIVEN: Reports automation is configured
        WHEN: Checking Makefile for generate-reports target
        THEN: Target should exist
        """
        makefile = Path("Makefile")
        content = makefile.read_text()

        assert "generate-reports:" in content, (
            "Makefile missing 'generate-reports' target\\n" "Expected: Target that regenerates all test infrastructure reports"
        )

        # Verify it's in .PHONY
        assert "generate-reports" in content.split(".PHONY:")[1].split("\\n")[0], (
            "'generate-reports' not in .PHONY declaration\\n" "Fix: Add to .PHONY line in Makefile"
        )
