"""
Composite Artifacts Service.

Orchestrates all storage layers for artifact operations:
- PostgreSQL (via RedisCachedArtifactsService): Primary storage with versioning
- Redis: Cache layer (wrapped in cached service)
- Cloud Storage: Hybrid storage for large content
- Qdrant: Vector embeddings for AI features

Features:
- Unified API for all artifact operations
- Automatic routing based on content size
- Graceful degradation on optional service failures
- User-scoped queries for security
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from mcp_server_langgraph.storage.artifacts.cloud_storage import (
        HybridCloudStorageService,
    )
    from mcp_server_langgraph.storage.artifacts.qdrant_service import (
        QdrantArtifactVectorService,
    )
    from mcp_server_langgraph.storage.artifacts.redis_cache import (
        RedisCachedArtifactsService,
    )


logger = logging.getLogger(__name__)


class CompositeArtifactsService:
    """
    Composite service orchestrating all artifact storage layers.

    This is the main entry point for artifact operations, coordinating:
    - Primary storage (PostgreSQL via cached service)
    - Cache layer (Redis, transparent via cached service)
    - Cloud storage (S3/GCS/Azure for large content)
    - Vector service (Qdrant for semantic search)

    Graceful degradation:
    - Vector indexing failures don't block CRUD operations
    - Cloud storage failures raise (content loss is critical)
    - Cache failures are handled by cached service
    """

    def __init__(
        self,
        cached_service: RedisCachedArtifactsService,
        cloud_storage: HybridCloudStorageService,
        vector_service: QdrantArtifactVectorService,
    ) -> None:
        """
        Initialize composite service.

        Args:
            cached_service: Redis-cached PostgreSQL service
            cloud_storage: Hybrid cloud storage for large content
            vector_service: Qdrant vector service for AI features
        """
        self._cached_service = cached_service
        self._cloud_storage = cloud_storage
        self._vector_service = vector_service

    async def create(
        self,
        session_id: str,
        user_id: str,
        artifact_type: str,
        title: str,
        content: str,
        content_type: str,
        edit_metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any] | None:
        """
        Create a new artifact.

        Orchestrates:
        1. Check content size for cloud storage routing
        2. Store in PostgreSQL (via cached service)
        3. Index in Qdrant for semantic search (best-effort)

        Args:
            session_id: Session ID
            user_id: User ID
            artifact_type: Artifact type (code, markdown, etc.)
            title: Artifact title
            content: Artifact content
            content_type: Content MIME type hint
            edit_metadata: Optional metadata

        Returns:
            Created artifact or None
        """
        # Step 1: Check cloud storage routing
        storage_info = await self._cloud_storage.upload(
            content=content,
            artifact_id="",  # Will be generated by DB
            user_id=user_id,
            content_type=content_type,
        )

        # Prepare content for DB storage
        # If stored in cloud, we don't store full content inline
        db_content = content if storage_info["storage_type"] == "inline" else ""

        # Step 2: Store in PostgreSQL
        artifact_data = {
            "session_id": session_id,
            "artifact_type": artifact_type,
            "title": title,
            "content": db_content,
            "content_type": content_type,
            "storage_type": storage_info["storage_type"],
            "storage_key": storage_info["storage_key"],
            "edit_metadata": edit_metadata,
        }
        artifact = await self._cached_service.create(artifact_data, user_id=user_id)

        # Step 3: Index in Qdrant (best-effort)
        try:
            # Use full content for embedding, not truncated DB content
            artifact_for_indexing = {**artifact, "content": content}
            await self._vector_service.index(artifact_for_indexing, user_id)
        except Exception as e:
            # Log but don't fail the operation
            logger.warning(
                "Failed to index artifact in vector service",
                extra={"artifact_id": artifact.get("id"), "error": str(e)},
            )

        return artifact

    async def get(
        self,
        artifact_id: str,
        user_id: str,
    ) -> dict[str, Any] | None:
        """
        Get artifact by ID.

        Orchestrates:
        1. Fetch metadata from cached service
        2. If stored in cloud, fetch content from cloud storage

        Args:
            artifact_id: Artifact ID
            user_id: User ID

        Returns:
            Artifact dict with full content or None
        """
        # Step 1: Get from cached service
        artifact = await self._cached_service.get(
            artifact_id=artifact_id,
            user_id=user_id,
        )

        if artifact is None:
            return None

        # Step 2: If stored in cloud, fetch content
        storage_type = artifact.get("storage_type", "inline")
        storage_key = artifact.get("storage_key")

        if storage_type != "inline" and storage_key:
            cloud_content = await self._cloud_storage.download(storage_key)
            if cloud_content is not None:
                artifact["content"] = cloud_content

        return artifact

    async def update(
        self,
        artifact_id: str,
        user_id: str,
        content: str | None = None,
        title: str | None = None,
        edit_metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any] | None:
        """
        Update an artifact.

        Orchestrates:
        1. Check content size for cloud storage routing (if content changed)
        2. Update in PostgreSQL
        3. Reindex in Qdrant (best-effort)

        Args:
            artifact_id: Artifact ID
            user_id: User ID
            content: New content (optional)
            title: New title (optional)
            edit_metadata: New metadata (optional)

        Returns:
            Updated artifact or None
        """
        storage_info = {"storage_type": "inline", "storage_key": None}
        db_content = content

        # Step 1: Check cloud storage routing if content changed
        if content is not None:
            storage_info = await self._cloud_storage.upload(
                content=content,
                artifact_id=artifact_id,
                user_id=user_id,
            )
            if storage_info["storage_type"] != "inline":
                db_content = ""

        # Step 2: Update in PostgreSQL
        update_data: dict[str, Any] = {}
        if db_content is not None:
            update_data["content"] = db_content
        if title is not None:
            update_data["title"] = title
        if storage_info["storage_type"]:
            update_data["storage_type"] = storage_info["storage_type"]
        if storage_info["storage_key"]:
            update_data["storage_key"] = storage_info["storage_key"]
        if edit_metadata is not None:
            update_data["edit_metadata"] = edit_metadata
        artifact = await self._cached_service.update(artifact_id, update_data, user_id=user_id)

        if artifact is None:
            return None

        # Step 3: Reindex in Qdrant (best-effort)
        try:
            artifact_for_indexing = {
                **artifact,
                "content": content if content else artifact.get("content", ""),
            }
            await self._vector_service.index(artifact_for_indexing, user_id)
        except Exception as e:
            logger.warning(
                "Failed to reindex artifact in vector service",
                extra={"artifact_id": artifact_id, "error": str(e)},
            )

        return artifact

    async def delete(
        self,
        artifact_id: str,
        user_id: str,
    ) -> bool:
        """
        Delete an artifact.

        Orchestrates:
        1. Get artifact metadata (for cloud storage key)
        2. Delete from PostgreSQL
        3. Delete from cloud storage (if applicable)
        4. Delete from Qdrant (best-effort)

        Args:
            artifact_id: Artifact ID
            user_id: User ID

        Returns:
            True if deleted, False otherwise
        """
        # Step 1: Get artifact metadata
        artifact = await self._cached_service.get(
            artifact_id=artifact_id,
            user_id=user_id,
        )

        if artifact is None:
            return False

        storage_key = artifact.get("storage_key")

        # Step 2: Delete from PostgreSQL
        deleted = await self._cached_service.delete(
            artifact_id=artifact_id,
            user_id=user_id,
        )

        if not deleted:
            return False

        # Step 3: Delete from cloud storage (if applicable)
        if storage_key:
            await self._cloud_storage.delete(storage_key)

        # Step 4: Delete from Qdrant (best-effort)
        try:
            await self._vector_service.delete(artifact_id=artifact_id)
        except Exception as e:
            logger.warning(
                "Failed to delete artifact from vector service",
                extra={"artifact_id": artifact_id, "error": str(e)},
            )

        return True

    async def list(
        self,
        user_id: str,
        session_id: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[dict[str, Any]]:
        """
        List artifacts for a user.

        Args:
            user_id: User ID
            session_id: Optional session filter
            limit: Max results
            offset: Pagination offset

        Returns:
            List of artifacts (metadata only, no full content)
        """
        # Note: Interface mismatch - RedisCachedArtifactsService.list uses cursor-based
        # pagination (no offset), returns tuple. This needs architectural review.
        result = await self._cached_service.list(
            user_id=user_id,
            session_id=session_id,
            limit=limit,
        )
        # Extract list from tuple (list, cursor, has_more)
        return result[0] if isinstance(result, tuple) else result

    async def get_versions(
        self,
        artifact_id: str,
        user_id: str,
        limit: int = 10,
    ) -> list[dict[str, Any]] | None:  # type: ignore[valid-type]
        """
        Get version history for an artifact.

        Args:
            artifact_id: Artifact ID
            user_id: User ID
            limit: Max versions to return

        Returns:
            List of versions or None if artifact not found
        """
        # Note: RedisCachedArtifactsService.get_versions doesn't support limit parameter
        # The limit is applied in the underlying repository
        return await self._cached_service.get_versions(
            artifact_id=artifact_id,
            user_id=user_id,
        )

    async def fork(
        self,
        artifact_id: str,
        user_id: str,
        new_name: str | None = None,
    ) -> dict[str, Any] | None:
        """
        Fork an artifact.

        Args:
            artifact_id: Source artifact ID
            user_id: User ID
            new_name: Optional new name for fork

        Returns:
            Forked artifact or None
        """
        forked = await self._cached_service.fork(
            artifact_id=artifact_id,
            user_id=user_id,
            new_name=new_name,
        )

        if forked is not None:
            # Index the forked artifact (best-effort)
            try:
                await self._vector_service.index(forked, user_id)
            except Exception as e:
                logger.warning(
                    "Failed to index forked artifact",
                    extra={"artifact_id": forked.get("id"), "error": str(e)},
                )

        return forked

    async def semantic_search(
        self,
        query: str,
        user_id: str,
        limit: int = 10,
    ) -> list[dict[str, Any]]:  # type: ignore[valid-type]
        """
        Semantic search across artifacts.

        Uses Qdrant vector service for similarity search.

        Args:
            query: Search query
            user_id: User ID (for filtering)
            limit: Max results

        Returns:
            List of search results with scores
        """
        try:
            return await self._vector_service.search(
                query=query,
                user_id=user_id,
                limit=limit,
            )
        except Exception as e:
            logger.warning(
                "Semantic search failed",
                extra={"query": query[:50], "error": str(e)},
            )
            return []

    async def find_similar(
        self,
        artifact_id: str,
        user_id: str,
        limit: int = 5,
    ) -> list[dict[str, Any]]:  # type: ignore[valid-type]
        """
        Find artifacts similar to a given artifact.

        Uses Qdrant vector service for similarity search.

        Args:
            artifact_id: Source artifact ID
            user_id: User ID (for filtering)
            limit: Max results

        Returns:
            List of similar artifacts
        """
        try:
            return await self._vector_service.find_similar(
                artifact_id=artifact_id,
                user_id=user_id,
                limit=limit,
            )
        except Exception as e:
            logger.warning(
                "Find similar failed",
                extra={"artifact_id": artifact_id, "error": str(e)},
            )
            return []
