#!/usr/bin/env bash
# start-worktree-session.sh
# Launches Claude Code in a new git worktree for isolated session work
#
# Usage:
#   ./scripts/start-worktree-session.sh [branch-name]
#
# If branch-name is not provided, uses current branch

set -euo pipefail

# Configuration
REPO_NAME="mcp-server-langgraph"
WORKTREES_DIR="../worktrees"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
WORKTREE_NAME="${REPO_NAME}-session-${TIMESTAMP}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Verify we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    log_error "Not in a git repository"
    exit 1
fi

# Get the repository root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

# Determine base branch
if [ $# -eq 1 ]; then
    BASE_BRANCH="$1"
    log_info "Using specified branch: $BASE_BRANCH"
else
    BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    log_info "Using current branch: $BASE_BRANCH"
fi

# Verify branch exists
if ! git rev-parse --verify "$BASE_BRANCH" > /dev/null 2>&1; then
    log_error "Branch '$BASE_BRANCH' does not exist"
    exit 1
fi

# Create worktrees directory if it doesn't exist
WORKTREES_PATH="${REPO_ROOT}/${WORKTREES_DIR}"
if [ ! -d "$WORKTREES_PATH" ]; then
    mkdir -p "$WORKTREES_PATH"
    log_success "Created worktrees directory: $WORKTREES_PATH"
fi

# Create the new worktree
WORKTREE_PATH="${WORKTREES_PATH}/${WORKTREE_NAME}"
log_info "Creating worktree: $WORKTREE_NAME"

# Create a new branch for this worktree session (based on BASE_BRANCH)
# This allows multiple worktrees to work independently
WORKTREE_BRANCH="${WORKTREE_NAME}"
if git worktree add -b "$WORKTREE_BRANCH" "$WORKTREE_PATH" "$BASE_BRANCH"; then
    log_success "Worktree created at: $WORKTREE_PATH"
    log_success "Branch: $WORKTREE_BRANCH (based on $BASE_BRANCH)"
else
    log_error "Failed to create worktree"
    exit 1
fi

# Create session metadata file
METADATA_FILE="${WORKTREE_PATH}/.claude-worktree-session"
cat > "$METADATA_FILE" << EOF
# Claude Code Worktree Session Metadata
# Auto-generated by start-worktree-session.sh
SESSION_ID=${WORKTREE_NAME}
WORKTREE_BRANCH=${WORKTREE_BRANCH}
BASE_BRANCH=${BASE_BRANCH}
CREATED_AT=${TIMESTAMP}
PARENT_REPO=${REPO_ROOT}
EOF

log_success "Session metadata created"

# Print session info
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Git Worktree Session Created${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${BLUE}Session:${NC}      $WORKTREE_NAME"
echo -e "${BLUE}Location:${NC}     $WORKTREE_PATH"
echo -e "${BLUE}Base Branch:${NC}  $BASE_BRANCH"
echo -e "${BLUE}Created:${NC}      $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if Claude Code is available
if command -v claude &> /dev/null; then
    log_info "Launching Claude Code in worktree..."
    echo ""

    # Export session info for hooks to detect
    export CLAUDE_WORKTREE_SESSION="$WORKTREE_NAME"
    export CLAUDE_WORKTREE_BASE_BRANCH="$BASE_BRANCH"

    # Change to worktree directory and launch Claude Code
    cd "$WORKTREE_PATH"
    claude

    # After Claude Code exits
    echo ""
    log_info "Claude Code session ended"

    # Check if worktree is clean (for potential auto-cleanup)
    if git diff-index --quiet HEAD -- 2>/dev/null; then
        echo ""
        log_warning "Worktree is clean (no uncommitted changes)"
        read -p "Delete this worktree? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            cd "$REPO_ROOT"
            if git worktree remove "$WORKTREE_PATH"; then
                log_success "Worktree deleted: $WORKTREE_NAME"
            else
                log_error "Failed to delete worktree"
            fi
        else
            log_info "Worktree preserved at: $WORKTREE_PATH"
        fi
    else
        echo ""
        log_info "Worktree has uncommitted changes - preserving"
        log_info "Location: $WORKTREE_PATH"
        echo ""
        log_info "To cleanup later, run: ./scripts/cleanup-worktrees.sh"
    fi
else
    log_warning "Claude Code CLI not found in PATH"
    log_info "To manually launch Claude Code in this worktree:"
    echo ""
    echo "  cd $WORKTREE_PATH"
    echo "  claude"
    echo ""
fi
