# ==============================================================================
# Help - Common Commands (Day-1 Developer)
# ==============================================================================

help-common:
	@echo "LangGraph MCP Agent - Common Commands (Quick Reference)"
	@echo ""
	@echo "Getting Started (< 5 minutes):"
	@echo "  1. make install-dev        # Install dependencies (~1 min)"
	@echo "  2. make quick-start        # Start with defaults (~2 min)"
	@echo "  3. make test-dev           # Verify everything works (~2-3 min)"
	@echo ""
	@echo "Daily Development:"
	@echo "  make test-dev              Run tests (fast, parallel, recommended)"
	@echo "  make validate-pre-push     Validate before push (matches CI exactly)"
	@echo "  make format                Format code (Ruff)"
	@echo "  make lint-check            Check code quality (Ruff, MyPy)"
	@echo "  make run-streamable        Start HTTP server"
	@echo ""
	@echo "Essential Testing:"
	@echo "  make test-unit             Unit tests with coverage"
	@echo "  make test-fast             All tests, skip coverage (faster)"
	@echo "  make test-integration      Integration tests (needs Docker)"
	@echo ""
	@echo "Infrastructure:"
	@echo "  make setup-infra           Start all Docker services"
	@echo "  make logs                  View service logs"
	@echo "  make clean                 Stop and cleanup"
	@echo ""
	@echo "Documentation:"
	@echo "  make help                  Full command reference"
	@echo "  make help-advanced         Advanced & specialized targets"
	@echo ""
	@echo "Pro Tips:"
	@echo "  - New here? See docs/day-1-developer.md for step-by-step guide"
	@echo "  - Use 'make -j4' for parallel execution (4x faster)"
	@echo "  - Use 'make test-dev' instead of 'make test' for development"
	@echo ""

# ==============================================================================
# Help - Full Reference
# ==============================================================================

help:
	@echo "LangGraph MCP Agent - Full Make Commands Reference"
	@echo ""
	@echo "NEW HERE? Run 'make help-common' for the essential commands"
	@echo ""
	@echo "Performance Tip:"
	@echo "  Use 'make -j4' to run independent targets in parallel (4 jobs)"
	@echo "  Example: 'make -j4 validate-all' runs all validations in parallel"
	@echo ""
	@echo "Setup:"
	@echo "  make install          Install prod dependencies"
	@echo "  make install-dev      Install development + test dependencies"
	@echo "  make setup-infra      Start Docker infrastructure"
	@echo "  make setup-openfga    Initialize OpenFGA"
	@echo "  make setup-keycloak   Initialize Keycloak"
	@echo "  make setup-infisical  Initialize Infisical"
	@echo ""
	@echo "Testing:"
	@echo "  make test             Run all tests with coverage"
	@echo "  make test-unit        Run pure unit tests"
	@echo "  make test-dev         Development mode (parallel, fast-fail)"
	@echo "  make test-fast        All tests without coverage"
	@echo "  make test-integration Integration tests in Docker"
	@echo "  make test-frontend    Frontend tests (sharded, parallel)"
	@echo "  make test-frontend-fast  Frontend tests (fast, 110 shards)"
	@echo "  make test-frontend-ci Frontend tests in CI mode (50 shards)"
	@echo "  make test-frontend-scripts  Run shell tests for sharded runner"
	@echo ""
	@echo "Validation:"
	@echo "  make validate-pre-push  Pre-push validation (CI-equivalent)"
	@echo "  make validate-all       Run all deployment validations"
	@echo ""
	@echo "Code Quality:"
	@echo "  make lint             Alias for lint-check"
	@echo "  make format           Alias for lint-fix"
	@echo "  make lint-check       Run Ruff linter + MyPy"
	@echo "  make lint-fix         Auto-fix with Ruff"
	@echo "  make security-check   Run security scans"
	@echo ""
	@echo "Running:"
	@echo "  make run              Run stdio MCP server"
	@echo "  make run-streamable   Run StreamableHTTP server"
	@echo "  make logs             Show infrastructure logs"
	@echo "  make health-check     Check system health"
	@echo ""
	@echo "Deployment:"
	@echo "  make deploy-dev       Deploy to development"
	@echo "  make deploy-stg   Deploy to stg"
	@echo "  make deploy-prod Deploy to prod"
	@echo ""
	@echo "Documentation:"
	@echo "  make docs-serve       Serve Mintlify docs locally"
	@echo "  make docs-build       Build Mintlify docs"
	@echo "  make docs-validate    Validate all documentation"
	@echo ""
	@echo "Cleanup:"
	@echo "  make clean            Stop containers and clean files"
	@echo "  make clean-all        Deep clean including venv"
	@echo ""

help-advanced:
	@echo "LangGraph MCP Agent - Advanced Commands"
	@echo ""
	@echo "Coverage:"
	@echo "  make test-coverage         Comprehensive coverage report"
	@echo "  make test-coverage-fast    Fast coverage (unit tests only)"
	@echo "  make test-coverage-html    HTML report only"
	@echo "  make test-coverage-xml     XML report only"
	@echo ""
	@echo "Quality Tests:"
	@echo "  make test-property         Property-based tests (Hypothesis)"
	@echo "  make test-contract         Contract tests (MCP, OpenAPI)"
	@echo "  make test-regression       Performance regression tests"
	@echo "  make test-mutation         Mutation tests (slow)"
	@echo ""
	@echo "Infrastructure:"
	@echo "  make test-infra-up         Start full test infrastructure"
	@echo "  make test-infra-down       Stop test infrastructure"
	@echo "  make test-e2e              Run end-to-end tests"
	@echo ""
	@echo "GKE STG:"
	@echo "  make gke-stg-up        Deploy complete GKE stg"
	@echo "  make gke-stg-down      Teardown GKE stg"
	@echo "  make gke-stg-status    Check GKE status"
	@echo ""
